### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#1]
Trying to require ``WebChimera.js.node`` by changing [this line](https://github.com/RSATom/WebChimera.js/blob/master/demos/ugly/index.html#L53) but always get:

    Uncaught Error: The specified module could not be found.
    [...]\WebChimera.js.node

Even with the direct path to the file (the path is correct though). Using the ``WebChimera.js.node`` from the releases page.

OS: Win 8.1
NW.js: v0.12.1 32bit

**Comment by RSATom** [comment]
It's possible it require Visual Studio 2013 CRT installed: https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by RSATom** [comment]
I'll fix it in the future versions.

**Comment by jaruba** [comment]
Do I need to install the 32bit version or 64bit? Curious as my OS is 64bit but node-webkit is 32bit.

I'm guessing the 32bit version?

**Comment by RSATom** [comment]
checked - yes, it's require mentioned above package installed.

**Comment by RSATom** [comment]
Current version only for 32bit. But it could be build for x64.

**Comment by RSATom** [comment]
@jaruba, sorry, have to go right now, will answer all questions tomorrow.

**Comment by jaruba** [comment]
I'll install Visual C++ 2013 CRT and will close the issue if it's working. :)

**Comment by Ivshti** [comment]
I think we can close this. Visual C++ 2013 CRT solves the issue.

@jaruba microsoft's site doesn't allow me to download the .exe at the moment (tried chrome & IE - the download doesn't start), so I used this: http://getintopc.com/softwares/utilities/visual-c-plus-plus-2013-redistributable-package-free-download/

**Comment by jaruba** [comment]
Pfft, I hacked that with ``Inspect Element`` in 30 seconds, it's trying to access a http link from a https loaded page and Chrome doesn't allow that.

Opening the http link from the error in the dev console in a new window downloads the file. :)

Still did not manage to get it working though as after installing Visual C++ 2013 CRT x86 I still get the same error, but started working on other things atm and will have to test this again later on, if it's some problem on my side, I'll close it.

**Comment by Ivshti** [comment]
@jaruba add VLC to your path (VideoLan/VLC directory). I tried that before I downloaded Visual C++ 2013.

**Comment by jaruba** [comment]
@Ivshti Yup! Works now! :+1: 

@RSATom

I would recommend changing the Download VLC link from [the Wiki Page](https://github.com/RSATom/WebChimera.js/wiki) to this one:

http://www.videolan.org/vlc/download-windows.html

For Windows at least, as it also has a zip archive, not only the binary.

**Comment by Ivshti** [comment]
The question now is how would this be packaged. I am thinking to create some pre-builds, at least for Mac and maybe linux, which are installable through npm. 
For windows, those would have to include at least the Visual C++ 2013 CRT (only the required components) and depend on the developer to embed VLC separately in their bundle.

**Comment by jaruba** [comment]
I'm sure @RSATom will find the solution so that end users will not need to install Visual C++ 2013 CRT.

As for packaging, the best solution would be for NW.js, VLC and WebChimera.js.node to be bundled together in a pre-packaged version that also includes some demo usage. Then it would be pretty easy to add to understand and add to any app.

**Comment by RSATom** [comment]
@Ivshti, yes I will avoid need install CRT in future version. Just need minor changes in cmake file.

**Comment by RSATom** [comment]
@jaruba, I've updeted link to VLC downloads, thanks for hint!

**Comment by Ivshti** [comment]
@RSATom as I said, I will try to do pre-builds for Electron (formerly atom-shell) that can be installed through npm. Seems like a great combo for me.

**Comment by RSATom** [comment]
@Ivshti, did you get the latest version working under `Electron`? Does it works well? What do you think about current perfomance?

**Comment by Ivshti** [comment]
No, I did not for now, I haven't managed to do a successful build on OS X. 

I am betting performance will be better than NW.js though, Electron has been more performant at anything for now. The technological principle behind integrating node.js modules is also the same, just a bit more elegantly implemented.

I will do a bit of experimentation today or tomorrow.
