### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by ADRIAGUSJO** [RSATom/WebChimera.js#101]

**Comment by jaruba** [comment]
_sounds serious_

**Comment by RSATom** [comment]
yes

**Comment by RSATom** [comment]
or maybe not...

**Comment by RSATom** [comment]
don't sure...

**Comment by Ivshti** [comment]
![issues](http://previews.123rf.com/images/stuartphoto/stuartphoto1403/stuartphoto140300269/26416343-Issues-Uphill-Character-Showing-Problems-Difficulty-Or-Troubles-Stock-Photo.jpg)

**Comment by Ivshti** [comment]
Go crazy -> http://www.shutterstock.com/cat.mhtml?search_source=base_landing_page&language=en&searchterm=issues

**Comment by RSATom** [comment]
it looks like solved...
