### ISSUE TITLE
Get current subtitle as text instead of hardcoding it on video

### ISSUE THREAD

**Issue by romaincointepas** [RSATom/WebChimera.js#102]
This may be a long shot, but I'm using Webchimera.js has a fallback renderer only and I would like to keep a single subtitles controller (for preferences purposes like font size, color, etc).

Being able to select one subtitle track and getting the content of the current subtitles for current playing time by text (event `onSubtitlesTextChanged`?) instead of Webchimera.js/VLC printing it would be great.

Is that something even remotely possible?

Thanks!
##

**Comment by RSATom** [comment]
Unfortunately, it's not supported by libvlc

**Comment by RSATom** [comment]
One possible solution could be use custom libvlc plugin, but don't sure 100%.

**Comment by jbkempf** [comment]
Well, I was thinking of having a tmem, to get an api similar to vmem, but with a text_renderer.

**Comment by RSATom** [comment]
Closed as too old.
