### ISSUE TITLE
Electron may be crashed with WebChimera on main process

### ISSUE THREAD

**Issue by yadex205** [RSATom/WebChimera.js#103]
Hi

I'm trying to create multi WebChimera.js instances on **Main Process** but electron often will be crashed a  few minutes later since app launched. When instantiate on renderer process, no problems happened...

In my app, six WC instances is created on main process and after about a minutes the app will be crashed.

Details by crash report is [here (gist)](https://gist.github.com/yadex205/9a63df288fd608c66a5d1def200c06bb).

And my environment is
- OS X 10.11 (MacBook Air with 4GB RAM)
- Electron 1.3.3, 1.3.5
- wcjs-prebuilt

Is it possible to create WC instance on Electron main process?

Thanks!

**Comment by RSATom** [comment]
How exactly did you install `WebChimera.js`?
Did you read this: https://github.com/RSATom/WebChimera.js/wiki/Due-to-bug-libvlc-2.2.x-could-not-be-used-as-is-outside-VLC.app-on-Mac-OS-X ?

**Comment by yadex205** [comment]
I used WebChimera.js via `wcjs-prebuilt` which obtains `WebChimera.js_v0.2.6_electron_v1.3.3_VLC_v2.2.4_x64_osx.tar.gz` automatically.

BTW, I forgot to assign WebChimera's instance to variable so I fix, and then above problem haven't been happened. I'm sorry, it looks like that this issue is by my mistake...

**Comment by RSATom** [comment]
Good news! So, when you will be sure issue was really gone, please close it.
