### ISSUE TITLE
Any ideas on VLC upstream/restructurization?

### ISSUE THREAD

**Issue by lyssdod** [RSATom/WebChimera.js#105]
Hi, are there any plans/ideas on using recent VLC source? I mean add a submodule of https://github.com/videolan/vlc/tree/master/lib and include it via `extern C` for the sake of simplification and eliminating the c-cpp shim?

**Comment by RSATom** [comment]
Don't understand what you mean.

Do you offer embed libvlc directly to Electron sources or something else?

**Comment by lyssdod** [comment]
No, just pick recent VLC sources and rewrite/change libvlc_wrapper

**Comment by RSATom** [comment]
if you just need latest VLC - use [nightlies binaries](http://nightlies.videolan.org/). There are no need rewrite something.
