### ISSUE TITLE
Buffered time ranges

### ISSUE THREAD

**Issue by romaincointepas** [RSATom/WebChimera.js#106]
Is there a way to get the equivalent of the HTML5 API `<video>.buffered` that returns an array of time ranges representing the parts that have been buffered?

See https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/buffering_seeking_time_ranges

It could be added to the current `onBuffering` event? (`onBuffering( percents, ranges )`)

**Comment by RSATom** [comment]
Don't think something like this available from libvlc...
All I can add to API are in following headers: https://github.com/RSATom/libvlc-sdk/tree/master/include/vlc

**Comment by romaincointepas** [comment]
@RSATom Would using a combination of the current `percents` argument multiplied by the `--network-caching` value give that info? (at least for the current buffered range).

Example:
- onBuffering, set the buffered range as:
> start: currentPosition
end: currentPosition + percents * --network-caching

- onTimeChanged, set the buffered range as:
> start: currentPosition
end: currentPosition + --network-caching

**Comment by RSATom** [comment]
@romaincointepas, maybe, I don't know what logic used inside libvlc for buffering
