### ISSUE TITLE
Downloaded release doesn't extract to node_modules

### ISSUE THREAD

**Issue by dragantl** [RSATom/WebChimera.js#108]
I have configured the environment that detects and downloads the following release:

![image](https://cloud.githubusercontent.com/assets/17302599/18942846/cb5bf8ce-85e9-11e6-8e69-11c262b2f5c8.png)

However, after the `zip` is downloaded, it is not installed or dropped into node_modules. Any ideas what is going on? I'm using nodejs 6.6.0 and npm 3.10.3.

**Comment by RSATom** [comment]
It's `wcjs-prebuilt` related. Please create issue there.

**Comment by dragantl** [comment]
Oops! I was sure I posted it to wcjs-prebuilt! Sorry!
