### ISSUE TITLE
Possible to change playback speed?

### ISSUE THREAD

**Issue by willnew** [RSATom/WebChimera.js#109]
Recently I'm trying to add some control buttons to my player, like speed up X1.5, X2, X3 and speed down, but didn't get much help from [https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API](Javascript API), I know webchimera wrapped libvlc, and VLC player do have speed buttons, so is it possible to change playback speed using Webchimera or libvlc inside it?

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API#vlcinput

> `rate`: input speed given as float (1.0 for normal speed, 0.5 for half speed, 2.0 for twice as fast, etc.).

**Comment by willnew** [comment]
shame on me. I didn't take a hard look on it, I'll have a try

**Comment by willnew** [comment]
@RSATom before close, I have another question to ask, in my project I want to get metadata from each frame(mostly datetime), and seems calling `onFrameReady` can only get attributes like height, width etc... do you have any comments on this?

**Comment by willnew** [comment]
Copy that, then I think I should search for a work around, thanks for your time 💯

**Comment by RSATom** [comment]
@willnew, btw, if you really need something like get video frame pts/dts, you could look to https://github.com/RSATom/wcjs-gs It provides this attributes.

**Comment by willnew** [comment]
@RSATom I'll take a look, thanks for letting me know that

**Comment by RSATom** [comment]
but keep in mind, wcjs-gs based on GStreamer, not libvlc
