### ISSUE TITLE
[announce] WebChimera.js will dead after VLC 3.0 release

### ISSUE THREAD

**Issue by RSATom** [RSATom/WebChimera.js#110]
https://forum.videolan.org/viewtopic.php?f=32&t=135545

It looks like since VLC 3.0 `vmem` will be even more broken. So if you still use `WebChimera.js` I would recommend you start search some alternative solution.

Sorry.

**Comment by jaruba** [comment]
![200](https://cloud.githubusercontent.com/assets/1777923/19766210/50f8b8ce-9c55-11e6-8664-69e1861edc4f.gif)

**Comment by romaincointepas** [comment]
@RSATom Any plans on supporting VLC 2.2.5 and maintaining it (making releases for new node versions)?

**Comment by RSATom** [comment]
@romaincointepas, since WebChimera.js buld is automated, it will be pretty easy maintain any VLC 2.2.x versions.

**Comment by jbkempf** [comment]
@RSATom there are work-arounds and we will get a solution. And seeing the additions in 3.0, I doubt it's a good idea to stay on 2.2.x.

**Comment by jaruba** [comment]
i did not expect JB to ever find this thread.. it's a christmas miracle..

![1439916660-haabt](https://cloud.githubusercontent.com/assets/1777923/21498526/eae96b08-cc35-11e6-8120-488be0c927cf.gif)

**Comment by jbkempf** [comment]
@jaruba I don't really like github, but since we (the VLC community) must do more around the JS ecosystem, and WC.js is the most advanced one around VLC, I doubt I have a choice :)

**Comment by RSATom** [comment]
> I doubt it's a good idea to stay on 2.2.x.

It's not about stay on 2.2.x, it's more about abandon WebChimera.js completely. And tbh it's almost happened already.

**Comment by jbkempf** [comment]
@RSATom ah, ok. Any special reason why?

**Comment by RSATom** [comment]
@jbkempf, just because we can't get good results with VLC 3.0 atm, and as you've mentioned, it's bad idea stay on outdated 2.x

But if there will be any reasonable solution - it's not a big deal to resurrect project.
I just don't have time to search reasonable solution for VLC 3.0, and don't sure I can.

**Comment by jbkempf** [comment]
@RSATom 3.0 is not finished yet. So dropping because there might be a big problem seems a bit weird.

Also, I'd argue you should use OpenGLES2 output mapped to webgl, because that would be way way faster.

**Comment by RSATom** [comment]
I just have to warn users, to give them time to switch to some other technology, since it could cost big amount of money for some of them.

**Comment by RSATom** [comment]
> Also, I'd argue you should use OpenGLES2 output mapped to webgl, because that would be way way faster.

Could you please explain what do you mean by "OpenGLES2 output mapped to webgl"?

**Comment by jbkempf** [comment]
You should be able to use the OpenGLES2 output of VLC and map it directly to a webgl context from CEF. I don't know yet how though.

**Comment by RSATom** [comment]
Understand. But unfortunately Node.js addons don't have access to low level OpenGL context used by WebGl. At least it was so about year ago. Maybe something was changed, don't know.

And yes, I'm agree,  it would be much better approach than current (with vmem).

**Comment by RiderSx** [comment]
So we'll pass `WebGLRenderingContext` from within JS code to native node module there is no way to use it?

**Comment by jbkempf** [comment]
I need to check, but there are ways, like emscripten is doing: https://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/EGL-Support-in-Emscripten.html

**Comment by RiderSx** [comment]
It'll be really good if you keep working on this one-and-only lib :) You know, there are no alternatives.

**Comment by jbkempf** [comment]
Well, as soon we add torrents to VLC, it'll be even better :)

**Comment by jaruba** [comment]
@jbkempf never thought u guys will make that step

**Comment by Ivshti** [comment]
@jbkempf "use the OpenGLES2 output of VLC and map it directly to a webgl context from CEF" - can you please elaborate on that?

**Comment by jbkempf** [comment]
@Ivshti sure. I'll do that on the other ticket.

**Comment by waliworld** [comment]
just found this project, sadpanda about vmem :( and while there isn't any real alternative right now, we are likely to have a client-side vlc.js at some point [through emscripten](http://ascii.textfiles.com/archives/5089)

Either way great project you got going here, even if release 3.0 changes might kill it :/

**Comment by RSATom** [comment]
As I know libvlc team finally solved problem with vmem in VLC 3.0. But I'm still don't sure I should resurrect this project. Just because this solution could not get well enough performance even with FullHD, say nothing of 4k..

**Comment by gamelaster** [comment]
This project is awesome, there is not any alternatives, please keep it up

**Comment by RSATom** [comment]
I was wrong, it looks like we will not have solution with vmem in the near future:
https://patches.videolan.org/patch/17206/

**Comment by itshaadi** [comment]
i had to install windows 7 on virtual box and then install all the requirements for compiling WebChimera. and now it's suspended ! 

![giphy](https://user-images.githubusercontent.com/10201704/29996900-6a1d4d72-901c-11e7-85f1-e3d61dc1bf93.gif)

**Comment by waliworld** [comment]
nah, I see your point here with this after reading the discussion on the patch. And yeah it does indeed struggle with HD content (of which all my shit is exactly that, no 4k atm but still). fair call here.

**Comment by jbkempf** [comment]
We're still looking for a good way to find a fast solution. PPAPI is one, but not a long term one.

**Comment by RSATom** [comment]
It's already dead.
