### ISSUE TITLE
ffmpeg instead of VLC

### ISSUE THREAD

**Issue by romaincointepas** [RSATom/WebChimera.js#111]
I was curious as to why ffmpeg can't be a replacement to VLC?

**Comment by RSATom** [comment]
It can. It just require some amount of work to do it.

**Comment by romaincointepas** [comment]
Got it. While there are probably many pros and cons for using ffmpeg instead of VLC, one (small) potential advantage I see would be reducing the size of webchimera.js (ffmpeg can be built to not include decoders and other features not needed by webchimera.js, ending up with a filesize of around 10-15MB). VLC is currently at ~75MB in the current webchimera.js, making the resulting node-webkit/electron app pretty big.

Can VLC also be compiled for "decoding" only, hence reducing the size of the embedded VLC dependency in webchimera.js?

**Comment by RSATom** [comment]
You could remove unnecessary VLC plugins to reduce app size. I can't do it since I don't know what plugins are required by your app.

**Comment by romaincointepas** [comment]
In the current VLC build embedded with webchimera.js, are there any dependencies that can't be used by webchimera.js at all? (I'm thinking encoders and such).

I'm thinking that even if "format support" may vary between apps, anything than webchimera.js can't use could be stripped at from the VLC embedded by default with webchimera.js.

Maybe I'm not seeing the bigger picture here, apologies if that's the case!

**Comment by RSATom** [comment]
[I've already removed some useless modules](https://github.com/RSATom/WebChimera.js/blob/master/appveyor_prepare_full_archive.cmd#L21), but can't be sure I've removed all.

**Comment by jbkempf** [comment]
@RSATom do you recompile VLC yourself? If so, configure with --disable-sout.
Else, you should be able to remove a lot more modules than what you have. Have you looked at our Android blacklist?

**Comment by RSATom** [comment]
> @RSATom do you recompile VLC yourself?

No, I prefer to use vanilla VLC packages from downloads.videolan.org

> Have you looked at our Android blacklist?

No, I didn't

**Comment by RSATom** [comment]
Closed as too old.
