### ISSUE TITLE
Nothing happens when i try to play video on Windows

### ISSUE THREAD

**Issue by blaremc** [RSATom/WebChimera.js#114]
I tried to compile and download different versions of webchimera.js and they do the same thing.
WebChimera.js is loaded, and everything seems okay. But nothing happens when i call play function.
I tried to copy vlc library from VLC install folder too.
Also I downloaded wcjs-ugly-demo and it doesn't work too.
Windows 7, 10
nwjs 18.8

This is console from ugly player.
![clip2net_170126002944](https://cloud.githubusercontent.com/assets/5220039/22311968/9d671e6c-e35e-11e6-8fb3-89331b2ad191.png)

**Comment by RSATom** [comment]
> `itemCount: 0`
It looks like playlist stay empty by some reason... Do you use latest `wcjs-ugly-demo`? It should log VLC debug messages to console too, but don't see it.

**Comment by blaremc** [comment]
This is a screenshot from the latest wcjs ugly demo

**Comment by RSATom** [comment]
@blaremc, is there any chance you have some old libvlc in your PATH?

**Comment by blaremc** [comment]
@RSATom i don't think so. If i delete libvlc from node_modules it's show me this error
![clip2net_170126122249](https://cloud.githubusercontent.com/assets/5220039/22327935/676486ba-e3c2-11e6-9bfd-b13a56fdb11c.png)

libvlc.dll version 2.2.2.0
Windows installed on bootcamp

**Comment by RSATom** [comment]
It looks like you need to read this: https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by blaremc** [comment]
You right it works, but how i fix it in build version?

**Comment by RSATom** [comment]
Don't understand your question.

**Comment by RSATom** [comment]
It can't be fixed. It's libvlc internal issue. All you can do - set `VLC_PLUGIN_PATH` env variable to workaround bug inside libvlc.

**Comment by blaremc** [comment]
@RSATom Thanks for help .
I mean, I'll create release application (.exe) and all libraries inside exe file. What path I should set? Or I have to copy plugins near exe file?

**Comment by RSATom** [comment]
libvlc will not work if will be packed inside (same for `WebChimera.js.node`). So you have to keep it somewhere near your .exe

**Comment by blaremc** [comment]
Thanks for answers! It works!
