### ISSUE TITLE
Skipped frames on 60 FPS video

### ISSUE THREAD

**Issue by limoragni** [RSATom/WebChimera.js#118]
Hey! I been reading the other Issues I hope you guys can find a way to work with VLC 3.0. This projects is crazy good. 

I'm using Webchimera on Electron and when using a 60fps video I'm getting from 1 to 20 frames dropped.  I'm checking this on the onFrameReady event.

Do you think this is the expected performance? Or there's something I could maybe do in order to avoid the frame dropping?

**Comment by jaruba** [comment]
are you sure it's not synchronous code of your's that's freezing the animation from time to time?

**Comment by Ivshti** [comment]
read this: https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues)

**Comment by RSATom** [comment]
Closed as too old.
