### ISSUE TITLE
Uncaught Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by baorr** [RSATom/WebChimera.js#120]
Uncaught Error: The specified procedure could not be found.
\\?\D:\works\git\mediaEditor\node-vlcPlayer-demo\node_modules\wcjs-prebuilt\bin\WebChimera.js.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\works\git\mediaEditor\node-vlcPlayer-demo\node_modules\wcjs-prebuilt\index.js:1:173)
    at Object.<anonymous> (D:\works\git\mediaEditor\node-vlcPlayer-demo\node_modules\wcjs-prebuilt\index.js:2:3)
![capture](https://cloud.githubusercontent.com/assets/553038/26190966/85705458-3bde-11e7-821a-5430fddd666b.PNG)

**Comment by RSATom** [comment]
What Electron version do you use?

**Comment by baorr** [comment]
here are my Build Prerequisites:
wcjs-prebuilt: WebChimera.js_v0.2.4_electron_v0.37.8_VLC_v2.2.2_ia32_win
electron 1.6.8 ia32
node 64bits 0.6.10.0
Visual Studio Community 2017
windows7 64bits

**Comment by baorr** [comment]
vlc and cmake are the latest version

**Comment by RSATom** [comment]
> wcjs-prebuilt: WebChimera.js_v0.2.4_**electron_v0.37.8**_VLC_v2.2.2_ia32_win
> **electron 1.6.8**

You have to use `WebChimera.js.node` built against your Electron version, or build it yourself.

**Comment by RSATom** [comment]
I'll try build it on my side, but don't sure if it still buildable.

**Comment by baorr** [comment]
thanks, can I do build it myself?

**Comment by RSATom** [comment]
Yes you can, just look in README

**Comment by baorr** [comment]
Here are the readme:

# WebChimera.js Player Demo

#### Description

Demo for [wcjs-player](https://github.com/jaruba/wcjs-player) showing WebChimera.js Player playing a single video. ``wcjs-player`` uses [WebChimera.js](https://github.com/RSATom/WebChimera.js) to draw the frames of libVLC to a canvas.

#### Demo Install

```
git clone https://github.com/jaruba/node-vlcPlayer-demo.git
cd node-vlcPlayer-demo
```

**Windows**
```
set WCJS_RUNTIME=electron
set WCJS_RUNTIME_VERSION=v0.37.6
set WCJS_VERSION=0.2.5
set WCJS_ARCH=ia32
```

**OSX/Linux**
```
export WCJS_RUNTIME="electron"
export WCJS_RUNTIME_VERSION="v0.37.6"
export WCJS_VERSION="0.2.5"
export WCJS_ARCH="ia32"
```

```
npm install
```

Now download Electron v0.37.6 for 32bit and run `app.js`

!! You can change the configuration values for `wcjs-prebuilt` according to your case, but keep in mind that the options are limited to the [prebuilt packages](https://github.com/RSATom/WebChimera.js/releases)

#### Screenshots

WebChimera.js Player running on NW.js (Windows)

<img src="http://webchimera.org/samples/wcjs-player.png">

WebChimera.js Player running on Electron (Mac)

<img src="http://webchimera.org/samples/wcjs-player-2.png">

**Comment by baorr** [comment]
I have tried this, but the same problem
Windows
set WCJS_RUNTIME=electron
set WCJS_RUNTIME_VERSION=v0.37.6
set WCJS_VERSION=0.2.5
set WCJS_ARCH=ia32
npm install

**Comment by RSATom** [comment]
I've forced rebuild on AppVeyor/Travis-CI - binaries will be available soon

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js#build-from-sources

**Comment by baorr** [comment]
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcDeinterlace.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcInput.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcMedia.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcMedia.h(6): fatal error C1083:
Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or direct
ory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlayer.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlaylist.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlaylist.h(6): fatal error C108
3: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dir
ectory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlaylistItems.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcSubtitles.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcVideo.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  NodeTools.cpp
  VlcVideoOutput.cpp
d:\works\git\mediaeditor\webchimera.js\src\VlcVideoOutput.h(11): fatal error C1
083: Cannot open include file: 'libvlc_wrapper/vlc_vmem.h': No such file or dir
ectory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  WebChimera.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]

![capture1](https://cloud.githubusercontent.com/assets/553038/26191988/9ccb1d96-3be2-11e7-9c27-8bd30b6a602f.PNG)

**Comment by baorr** [comment]
when I build it, it goes like this.

**Comment by baorr** [comment]
It was all I can found in the folder libvlc_wrapper
![capture2](https://cloud.githubusercontent.com/assets/553038/26192099/faeb6f5c-3be2-11e7-895c-a62509cea572.PNG)

**Comment by baorr** [comment]
I just use Visual Studio Community 2013 only?

**Comment by baorr** [comment]
# **can you solve this problem, so I can build it myself, thanks.**


d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcDeinterlace.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcInput.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcMedia.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcMedia.h(6): fatal error C1083:
Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or direct
ory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlayer.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlaylist.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlaylist.h(6): fatal error C108
3: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dir
ectory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcPlaylistItems.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcSubtitles.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  JsVlcVideo.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  NodeTools.cpp
  VlcVideoOutput.cpp
d:\works\git\mediaeditor\webchimera.js\src\VlcVideoOutput.h(11): fatal error C1
083: Cannot open include file: 'libvlc_wrapper/vlc_vmem.h': No such file or dir
ectory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]
  WebChimera.cpp
d:\works\git\mediaeditor\webchimera.js\src\JsVlcPlayer.h(12): fatal error C1083
: Cannot open include file: 'libvlc_wrapper/vlc_player.h': No such file or dire
ctory [D:\works\git\mediaEditor\WebChimera.js\build\WebChimera.js.vcxproj]

![capture1](https://cloud.githubusercontent.com/assets/553038/26191988/9ccb1d96-3be2-11e7-9c27-8bd30b6a602f.PNG)

**Comment by baorr** [comment]
hi, Sergey
I have used Visual Studio 2013，but problem is the same

**Comment by RSATom** [comment]
You should do `git submodule update --init --recursive` before buld, or clone with `--recursive` flag.

**Comment by baorr** [comment]
Thanks, Sergey. It works.
