### ISSUE TITLE
build_electron.cmd  Error

### ISSUE THREAD

**Issue by zgangjin** [RSATom/WebChimera.js#121]
![image](https://cloud.githubusercontent.com/assets/19166110/26237850/5ef36a2e-3ca9-11e7-9e6d-3ca74bf3dc98.png)

Please help me look at it

**Comment by RSATom** [comment]
it looks like you don't have Visual Studio installed

**Comment by zgangjin** [comment]
I installed it Visual Studio2013

**Comment by zgangjin** [comment]
At the beginning of the installation of 2017, later changed to 2013

**Comment by RSATom** [comment]
It should work with VS 2017 too, just didn't try it myself. So, do you still have the same error?

**Comment by walldir** [comment]
I have the same problem:

![image](https://cloud.githubusercontent.com/assets/8962359/26506725/ddb40650-4223-11e7-81a8-342289524226.png)

**Comment by RSATom** [comment]
Do you have cmake installed?

**Comment by CHQ930731** [comment]
install cmake and add it's installation path to environment variable.

**Comment by RSATom** [comment]
Closed as too old.
