### ISSUE TITLE
Video not showing in electron 

### ISSUE THREAD

**Issue by Hommey** [RSATom/WebChimera.js#125]
Hi,

I'm able to use webchimera (renderer) with electron 1.4.13 to display video from rtsp source on debian stretch.
For some reasons i need to use debian wheezy with vlc 2.1.5 from wheezy backports.

Everything is fine during installation and compilation but when i try to display video, electron log says everything is ok but no videos appears in the canvas.

Can you help me on this ?

Thanks

**Comment by RSATom** [comment]
This project is suspended, I don't plan do any support until (and if) it will be resurrected.  Sorry.

**Comment by Hommey** [comment]
Hi,
Ok thanks I understand that.

But without doing any support can you said to me if vlc 2.1.5 should works or only 2.2.x is supported on linux ?

Thanks

Val.

**Comment by RSATom** [comment]
2.1.5 should work, but you should read this: https://github.com/RSATom/WebChimera.js/issues/69

**Comment by RSATom** [comment]
Closed as too old.
