### ISSUE TITLE
Build-essential instead of build-essentials on instructions for Linux...

### ISSUE THREAD

**Issue by holodny** [RSATom/WebChimera.js#13]
That was the only thing I ran into following your directions.  This is really sweet!  I was looking at building something on nwjs using WebRTC or MediaRecorder but it's either not mature enough or not supported yet so I was looking to revert to VLC and came across your project.  You mentioned not knowing what a typical use case for Webchimera might be... I built a multimedia application that records/plays back from four cameras and a microphone(s) on C# using VLC libraries and I was looking to do similar with nwjs, thinking that it will be a much faster application development/prototyping environment and that I could focus more on javascript, HTML5 and the other web stuff that I work with daily instead of having to switch to C# or other stuff on the desktop.

**Comment by RSATom** [comment]
>  Build-essential instead of build-essentials

Thank you for your report, will fix it soon.

And thank you for your support and sharing your experience. I'm very appreciate it.

**Comment by RSATom** [comment]
Typo fixed. Thanks!
