### ISSUE TITLE
was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by zgangjin** [RSATom/WebChimera.js#132]
Error: The module '\\?\C:\Users\gangjinzhang\AppData\Local\Programs\oms-client\resources\app.asar.unpacked\node_modules\wcjs-prebuilt\bin\WebChimera.js.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

How do you deal with such a problem?
`npm rebuild` did not try to solve it

**Comment by zgangjin** [comment]
build_electron.cmd did not try to solve it
In the process of trying   build_node.cmd

**Comment by zgangjin** [comment]
Electron updates to the latest version can be thanks
Before it should be packed with the latest version used by ’electron-builder‘

**Comment by RSATom** [comment]
Sorry, don't understand you

**Comment by zgangjin** [comment]
I used the  ’electron-builder‘ package my application, it uses the latest 1.8.4, not the 1.7.10 I installed, so there is a problem of the version is not uniform

**Comment by RSATom** [comment]
If you solved your problem, please close this issue.
