### ISSUE TITLE
It's not compatible with the latest Electron versions

### ISSUE THREAD

**Issue by RSATom** [RSATom/WebChimera.js#134]
v8 Engine was changed very significantly.

**Comment by RSATom** [comment]
Looks useful: https://github.com/cmake-js/cmake-js/issues/222

**Comment by RSATom** [comment]
Some progress: https://github.com/RSATom/WebChimera.js/tree/wip

**Comment by alexandrucancescu** [comment]
Do you plan to support other platforms beside windows? There are no prebuilts for macos and the old ones do not work with new node versions, also it does not build from source when using node 14.

**Comment by RSATom** [comment]
@alexandrucancescu Right now I've managed to fix compatibility issues with the latest Electron versions only on Linux. Published version for for Windows you can see in Releases is still broken. I'm still trying to fix it. After that I'll try to fix Mac OS version and latest Node.js compatibility. But don't sure how much time it could take...

**Comment by RSATom** [comment]
@alexandrucancescu btw, why do you need Node.js version? What tasks do you want to solve with it? The reason why I'm asking, maybe https://github.com/RSATom/wcjs-gs will be more suitable if you plan use it on some backend. I'm using it myself for some audio processing tasks on Amazon EC2 instances. But unfortunately it has limited API atm...

**Comment by alexandrucancescu** [comment]
Thanks for your response and for maintaining this awesome project.

My use case is using WebChimera in an electron app to render videos on a canvas. I've been keeping an eye on this project for a couple of years now as I don't have the knowledge to integrate VLC myself into an electron app.

**Comment by RSATom** [comment]
@alexandrucancescu please keep in mind, you will not be able get good performance with it, especially with big resolution videos/streams (FullHD and upper)

**Comment by RSATom** [comment]
Looks useful to get Windows build working: https://github.com/cmake-js/cmake-js/issues/153

**Comment by RSATom** [comment]
I hope I was able fix at least minimal required amount of compatibility issues to be able at least run it... Please test if you are interested.

**Comment by mattzucker** [comment]
I was not able to get https://github.com/RSATom/wcjs-ugly-demo working with Electron 12.0.0 and WebChimera v0.3.1b on Windows.  Electron would crash and show an empty all white screen with no error message.  Reverting to Electron 11.1.0 and WebChimera v0.3.1 works.
Can you look into fixing this for the latest Electron?

**Comment by RSATom** [comment]
@mattzucker created separate ticket.
