### ISSUE TITLE
Push the new changes to npm

### ISSUE THREAD

**Issue by ramtinsoltani** [RSATom/WebChimera.js#137]
The npm package has not been updated in 4 years. Would you push the latest changes to npm?

**Comment by RSATom** [comment]
Done. But don't think it will help you much, since anyway you will have to build it on install, and in such case there is no difference in install from npm and install from github directly.

**Comment by ramtinsoltani** [comment]
Wow! Thanks for the quick response. Just a question though... Wouldn't not having it installed from npm result in `node_modules/webchimera.js` being deleted on future npm installs?

**Comment by RSATom** [comment]
Don't think so, if you add it to dependencies to `package.json` as reference to GitHub repo.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies
