### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by sjames272727** [RSATom/WebChimera.js#139]
Does WebChimera work with ES6? I'm trying to use it with react.js but can't get it to work.

I've tried putting the windows pre-built in node_modules and importing in with ES6 modules like `import wc from "webchimera.js"`, but that doesn't work.

**Comment by RSATom** [comment]
Initially it was implemented for Node.js and derivatives so used CommonJS modules. I don't have any plans to add ES6 modules support since don't see any reason to spend my (very limited) time on it.

**Comment by sjames272727** [comment]
Ok, thanks anyways for this great project. I'll close the issue now.
