### ISSUE TITLE
Electron with Vue/webpack crash when creating player

### ISSUE THREAD

**Issue by dbussert** [RSATom/WebChimera.js#143]
I have `wcjs-prebuilt` working fine in a basic electron app, but when I add it to a Vue electron app, the app crashes when `.createPlayer()` is called. I've only tested this issue on Win x64, using `wcjs-prebuilt` because this was the most stable versions of precompiled binaries.

```
	"wcjs-prebuilt": {
		"runtime": "electron",
		"runtimeVersion": "v11.1.0",
		"version": "v0.3.1"
	},
```

I've created a sample hello world app that demonstrates the issue. The `README.md` explains how to test it: https://github.com/dbussert/wcjs-vue-hello-world

**Comment by RSATom** [comment]
Did you see https://github.com/RSATom/WebChimera.js/wiki/WebChimera.js-with-Webpack ?

**Comment by dbussert** [comment]
Yes, I'm using the recommend node-loader and `wcjs-prebuilt` is set to ASAR external. Electron starts fine when requiring `wcjs-prebuilt` and I can see the `wcjs` object has a VLC version, so I believe webpacked is handling it correctly. The issue is only when calling `createPlayer()`

**Comment by dbussert** [comment]
The only difference in the webpack externals is the Vue electron-builder wraps the webpack config, and it takes the externals as an array name of dependencies only, not an object as your example provides. However I believe the externals is working, since there's no build time issues with the `.node` file

**Comment by dbussert** [comment]
Comparing now, it appears Vue electron builder might require 2 entries for externals. https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/223. Following that it's not crashing, so I will test if that's a complete fix.

**Comment by dbussert** [comment]
After further testing, although it doesn't crash after adding a 2nd externals entry, the crated player does not play (no starting, no messages logged). There's still something wrong in this scenario

**Comment by RSATom** [comment]
The main problem with .node addons - they should reside as regular file on target system. Internally it's just regular .dll (on Windows, .so on Linux, .dylib on Mac OS) file, and system could not load it from any sort of archive. So as dirty workaround you could try just specify full path to `WebChimera.js.node` file to `require`

**Comment by dbussert** [comment]
Thanks, that helped, it turns out my `VLC_PLUGIN_PATH` was incorrect because the Vue server changes `__dirname`. Without the `VLC_PLUGIN_PATH` being correct, wcjs would load, but nothing would happen.
