### ISSUE TITLE
How to get snapshot from wcjs player using javascript

### ISSUE THREAD

**Issue by vihar1996** [RSATom/WebChimera.js#145]
I got the uint8array but i am unable to process it to an image

**Comment by boonzie** [comment]
use webgl video renderer to render it into canvas

**Comment by vihar1996** [comment]
i am new to this field so can you please send me code sample for this

**Comment by vihar1996** [comment]
thank you so much it worked

**Comment by dbussert** [comment]
can you post what you used as an example for others?

**Comment by vihar1996** [comment]
var canvas = document.getElementById("your-canvas-id");
var renderContext = require("webgl-video-renderer").setupCanvas(canvas);

var player = require("webchimera.js").createPlayer();
player.onFrameReady =
    function(frame) {
        renderContext.render(frame, frame.width, frame.height, frame.uOffset, frame.vOffset);
    }

player.play("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");

once the player starts playing you can get the snapshot/images using canvas.toDataURL()
