### ISSUE TITLE
onFrameReady not called

### ISSUE THREAD

**Issue by NotixOfficial** [RSATom/WebChimera.js#147]
onFrameReady callback is not called after creating a new BrowserWindow, or when doing CTRL + R.

**Comment by RSATom** [comment]
@NotixOfficial Did you try https://github.com/RSATom/wcjs-ugly-demo?

**Comment by NotixOfficial** [comment]
Yeah it's the same

**Comment by RSATom** [comment]
What OS do you use?

> onFrameReady callback is not called after creating a new BrowserWindow

What does it means? Do you try open second window, or you are able to see the problem right after start `wcjs-ugly-demo`?

**Comment by NotixOfficial** [comment]
Yeah the problem is on demo also. When you start it first time it works well, but after CTRL + R app recives lower amount of frames. Im using Windows 10 Latest Build.

**Comment by hondek** [comment]
in my case help when i set
``app.allowRendererProcessReuse = false;``
