### ISSUE TITLE
Join the LibVLC community discord server

### ISSUE THREAD

**Issue by mfkl** [RSATom/WebChimera.js#148]
Hi,

Great work!

Are you interested in joining our [Libvlc community discord server](https://discord.gg/3h3K3JF)? We have people from various ecosystems already (python, c++, dart, java, c#, go, etc.) and would love to have you!

If you're interested, I'll create a channel for webchimera/electron and I'll open a PR to update your README.

Cheers

**Comment by RSATom** [comment]
@mfkl is VLC IRC channel dead already? If all VLC related discussions was moved to Discord - I'm Ok to be there too. And will be glad to your help with that. Thank you!

**Comment by mfkl** [comment]
VLC IRC is still alive, we moved to libera.chat (see https://github.com/videolan/vlc#contributing--community).

The IRC is mostly for core dev and the main app. The discord is aimed for LibVLC bindings maintainers and users :-)

Closing as you're aware of this issue already 👍
