### ISSUE TITLE
[VLC Linux version] Does webchimera does not work with vlc greater than 2.2.2?

### ISSUE THREAD

**Issue by hnguyen48206** [RSATom/WebChimera.js#155]
Hi,

I'm using NW.js to build a video streaming app with Webchimera. So far, it has been working without any problem on Windows 10 (+ lastest VLC installed). However, on Linux, when I start the nwj app (already built one), it only works on Ubuntu 16 (vlc 2.2.2) but not ubuntu 20 (vlc 3.x). The reason why I wonder if this is due to VLC because the On Encounter Error call back has been called with 'undefined' error (I'm not so sure if the way the event has been declared was correct or not).

Below is the function I used to play the streaming. My nwjs and webchimera dev versions are 0.18.1 and 0.2.7 .Many thanks. 

```
function playVideo() {
				console.log('Play hit!')
				try {
					webChimeraPlayer.onLogMessage =
						function (level, message, format) {
							// console.log(message);
						}
					webChimeraPlayer.onFrameReady =
						function (frame) {
							renderContext.render(frame, frame.width, frame.height, frame.uOffset, frame.vOffset);
						}
					webChimeraPlayer.onEncounteredError =
						function (error) {
							console.log('vlc error', error)
						}
					webChimeraPlayer.play('http://10.70.123.62:80/streams/xxx/stream/xxx.m3u8');	

				} catch (error) {
					console.log(error)
				}
}
```

**Comment by RSATom** [comment]
It's broken on linux: https://github.com/RSATom/WebChimera.js/issues/69
