### ISSUE TITLE
npm config support in CMake.js

### ISSUE THREAD

**Issue by unbornchikken** [RSATom/WebChimera.js#16]
Hi,

https://github.com/unbornchikken/cmake-js#npm-config-integration

Hope it helps!

**Comment by RSATom** [comment]
Thank you Gábor! All that I miss now is possibility setup config parameters directly in `npm install`: 
https://github.com/npm/npm/issues/8431 It's possible setup temporary parameters via environment variables like `npm_config_xxx` but it's not very convenient.

**Comment by unbornchikken** [comment]
Try this on win:

set foo=bar&&npm install

and in CMakeLists.txt:

message(STATUS $ENV{foo})

Kinda ugly, but it should do.

**Comment by RSATom** [comment]
Thanks, it should work.
Anyway I hope guys from npm team will answer me something...

**Comment by RSATom** [comment]
@unbornchikken, is it possible override `runtime` and `runtime_version` for `cmake-js` via npm config?

**Comment by unbornchikken** [comment]
No they are not overrideable, because npm config is global for all node installations, so if you set something for compiling NW.js stuff, then Node.js, io.js, oi.js, sj.io and co. are gonna use that. (There is only one .npmrc file in your home folder.)

This stuff is for configuring external dependencies or some environmental stuff, like AF_PATH in [Fire.js](https://github.com/unbornchikken/fire-js).

**Comment by RSATom** [comment]
understand, thanks for explaining.

**Comment by RSATom** [comment]
@unbornchikken, is it possible run `cmake-js` from .js script?

**Comment by unbornchikken** [comment]
It's designed to act as a class library as well. The entry point is the BuildSystem class. Unfortunattely I ain't got documentation or examples, but just take a look at the binary script, it's pretty straightforward.

**Comment by RSATom** [comment]
could you please give small example how I could run something same as `cmake-js rebuild` from js?

**Comment by unbornchikken** [comment]
```js
var cmakeJS = require("cmake-js");
var BuildSystem = cmakeJS.BuildSystem;

var options = { ... };
var buildSystem = new BuildSystem(options);
buildSystem.build()
    .then(function() {
        console.log("OK");
    },
    function(e) {
        consle.error(e.stack);
    });
```

Available commands are there: https://github.com/unbornchikken/cmake-js/blob/master/bin/cmake-js#L149

Available options are there: https://github.com/unbornchikken/cmake-js/blob/master/bin/cmake-js#L114

It logs to console by default, but that can be turned off by setting options.noLog = true. In this case you can turn on debug logging by setting the environment variable DEBUG="cmake-js". It's handled by the standard debug module. See there: https://github.com/unbornchikken/cmake-js/blob/master/lib/cmLog.js

**Comment by RSATom** [comment]
Thank you Gábor, it's exactly what I need.
