### ISSUE TITLE
Out of tree module with AVI fix

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#18]
This is related to VLC's bug with loading AVi length / seeking in AVI files over http.

This is not really related to WebChimera.js, but it's a nasty bug, so if we provide the solution it could only lead to good things for WebChimera.js

VLC 2.2 almost provided the solution, but the patch that makes it work is here: https://github.com/Ivshti/vlc-2.2/commit/b65ed7b2d4c82c74d387a819c7e2d8e7b0f58548

I'm opening an issue so that we know that we remember it. And a finalized solution would be an out-of-tree VLC module for the AVI demuxer, which can serve as a drop-in solution and be built using webchimera.js' infrastructure.

This will help: https://wiki.videolan.org/OutOfTreeCompile/
##

**Comment by RSATom** [comment]
Thanks, accepted!

**Comment by Ivshti** [comment]
As we discussed, for the far future we might have a webchimera.js version over libav or gstreamer.

libav would require more work, but it's a minimalistic (in terms of overhead) solution, may provide better performance and get rid of some of these issues.

As for the gstreamer idea, I'm personally skeptical because of cross-platform issues with GStreamer. But that was in the past, they may have resolved them.

**Comment by jbkempf** [comment]
I believe that we fixed the AVI issue in 3.0

**Comment by RSATom** [comment]
Closed as too old.
