### ISSUE TITLE
libvlc uses swscale when display resolution / resolution are different

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#19]
In the frame setup callback, VLC gives as a width/high which correspond to the video resolution.

However, it decodes to the video "display resolution",  which is already the very resolution we want to decode to.

For a video stream which VLC gives in it's "media information" window:

```
Resolution 720x418
Display Resolution 720x404
```

We get 720 and 418 in our frame setup callback. Which is the actual video frame size.
However, since VLC already decodes to the "display resolution", it initiates swscale to convert it back to 720x418.

This is the output of ffprobe:

```
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 720x404, 1116 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
```

Which detects the "Display Resolution".

This is the libvlc output from the VLC app

```
[00000001029082b8] swscale scale debug: 32x32 (32x32) chroma: YUVA -> 16x16 (16x16) chroma: RGBA with scaling using Bicubic (good quality)
```

And this is from WebChimera.js

```
[00007fb1f41630b8] swscale filter debug: 720x404 (720x418) chroma: I420 -> 720x418 (720x418) chroma: I420 with scaling using Bicubic (good quality)
```
##

**Comment by RSATom** [comment]
will be solved with https://github.com/RSATom/vmem2

**Comment by RSATom** [comment]
Closed as too old.
