### ISSUE TITLE
OS X building 

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#2]
I tried to build Webchimera.js on OS X and the errors I get are C++11-related:

E.g.
```
[8/12] Building CXX object deps/libvlc_wrapper/CMakeFiles/libvlc_wrapper.dir/vlc_audio.cpp.o
FAILED: /usr/bin/clang++    -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -w -O3 -DNDEBUG -I/Users/ivogeorgiev/.cmake-js/nw-ia32/v0.12.1/src -I/Users/ivogeorgiev/.cmake-js/nw-ia32/v0.12.1/deps/v8/include -I/Users/ivogeorgiev/.cmake-js/nw-ia32/v0.12.1/deps/uv/include -I../deps -I../deps/libvlc-sdk/include -MMD -MT deps/libvlc_wrapper/CMakeFiles/libvlc_wrapper.dir/vlc_audio.cpp.o -MF deps/libvlc_wrapper/CMakeFiles/libvlc_wrapper.dir/vlc_audio.cpp.o.d -o deps/libvlc_wrapper/CMakeFiles/libvlc_wrapper.dir/vlc_audio.cpp.o -c ../deps/libvlc_wrapper/vlc_audio.cpp
../deps/libvlc_wrapper/vlc_audio.cpp:35:9: error: expected expression
        [event] ( audio_events_callback* callback )
```

What I did is added 
```
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++")
```
To every CMakeLists.txt (in root and libvlcwrapper), after files,include_directories,add_subdirectory lines. 

Now it compiles but I am still resolving the issue with libvlc.lib linkage.

May I ask why cmake is used instead of node-gyp? After all this is a node.js module

**Comment by RSATom** [comment]
I just more familliar with `cmake` than `node-gyp`, and another reason google plan deprecate `gyp`...

**Comment by RSATom** [comment]
http://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake - it could be useful

**Comment by Ivshti** [comment]
Yeah, I fixed the C++11 part with what I wrote, but the issue now is VLC linking. I linked it statically against libvlc (https://github.com/Ivshti/WebChimera.js/commit/ea64db213105121ed9a3782ceb766929b4e1266f) but it complains of

```
[55326:0515/160116:INFO:CONSOLE(346)] "Uncaught Error: dlopen(/private/tmp/WebChimera.js/build/release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /private/tmp/WebChimera.js/build/release/WebChimera.js.node
  Reason: image not found", source: module.js (346)
```

**Comment by RSATom** [comment]
I think placing libvlc.dylib to path will not help on Mac, I think you have to place all libvlc files somewhere near WebChimera.js.node or NW.js executable

**Comment by Ivshti** [comment]
That's what I did in general - included all in lib/ ; however since I did it completely blindly, without knowing how libvlc should be embedded, so I doubt I've done it right.

**Comment by RSATom** [comment]
I'll try to take look on it next week (I have some trip right now).

**Comment by Ivshti** [comment]
I just submitted a pull request fixing building on Mac. It's not that tidy since the path to VLC is hardcoded.

Also I need to point out that VLC dirs ``plugins`` and ``lib`` need to be copied to build/Release which is the @loader_path

**Comment by RSATom** [comment]
> Also I need to point out that VLC dirs plugins and lib need to be copied to build/Release which is the @loader_path

Yes, it's has a meaning. Thanks for hint.

**Comment by Ivshti** [comment]
@RSATom a version that builds with Electron is now in Ivshti/WebChimera.js repo,  I modified cmake-js to support Electron and added the uv.h header - that was everything needed. 

For me, on OS X it uses more than two times less CPU than NW.js does. On Windows there's less difference between the performance of NW.js and Electron, but I still bet it would be a bit better under Electron.

**Comment by RSATom** [comment]
Good job @Ivshti !

It seems we need CI server to simplify building `WebChimera.js` for variety platforms and engines...

Btw, I did some optimizations which will be available at repo soon, so load will be even less - I've excluded `memcpy` of video frames.

**Comment by Ivshti** [comment]
Awesome :) It's been performing decently already, I imagine with this WebChimera.js's performance will be on the same level (if not better) than HTML5 <video>. 

In other news, I changed the init code of the demo a bit - https://github.com/Ivshti/WebChimera.js/commit/e2fe5e40d45645ef2264695093447778f5de0b72 so that it draws on the full canvas size instead of a tiny video in the bottom left.

**Comment by RSATom** [comment]
I hope so :) And one more optimization is still pending: now frames are decoded to `RGBA` pixel format, but it's better decode it to `I420` pixel format

**Comment by Ivshti** [comment]
Yeah, I noticed that. And usually RGBA to I420 boosts performance a lot so I am really looking forward to this.

**Comment by jaruba** [comment]
This is history in the making. Good job @Ivshti for Atom/Electron support!

Can't wait to see this project in it's maturity so I can do some JavaScript voodoo on it! :)

**Comment by Ivshti** [comment]
I agree! And @RSATom is a genius for thinking of this.

When we verify building on OS X is OK we can close this. Someone should probably open a thread about the API. I'll probably write an HTML5 <video>-compatible shim, whatever the API is - I'm guessing it will be based on the VLC API.

**Comment by RSATom** [comment]
:)

About API - I plan to do it almost identical to current [WebChimera API](http://wiki.webchimera.org/Plugin_JavaScript_API)

**Comment by Ivshti** [comment]
@RSATom is the wip branch currently compilable? I tried when you pushed it and got a few errors, looked like missing arguments, and I decided that it wasn't compilable yet?

**Comment by RSATom** [comment]
You shouldn't use `wip` branch at all - it's branch for my experiments, and it's very possible it will be totally reworked.

**Comment by Ivshti** [comment]
Just wanted to see what's cooking :) Seems interesting

**Comment by RSATom** [comment]
Ok, just don't rely on it

**Comment by Ivshti** [comment]
Sure. BTW doing a 
```cpp
_tmpFrameBuffer.swap( const std::vector<char>() )
```
Causes this on clang compiler: `` error: non-const lvalue reference to type 'vector<[2 * ...]>' cannot bind to a temporary of type 'vector<[2 * ...]>'``

The alternative is:
```cpp
std::vector<char>().swap(_tmpFrameBuffer);
```

**Comment by RSATom** [comment]
Thanks, I'll fix it

**Comment by RSATom** [comment]
@Ivshti, could we treat it as fixed?

**Comment by Ivshti** [comment]
Sure.
