### ISSUE TITLE
Event Propagation

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#20]
Events don't currently work in ``wcjs-player`` because each newly attached listener overwrites the player's listener and the UI stops functioning.

**Comment by RSATom** [comment]
`VlcPlayer.events` property added, which will return `EventsEmitter`... Will try publish it to npm at evening.

**Comment by jaruba** [comment]
How would this be used?

**Comment by RSATom** [comment]
something like this

    VlcPlayer.events.on( "PositionChanged", function(position) { console.log(position); } );

**Comment by jaruba** [comment]
Great, can't wait to try it out. :)

**Comment by RSATom** [comment]
it's already in npm

**Comment by jaruba** [comment]
tested, works perfectly :)

**Comment by RSATom** [comment]
good :)
