### ISSUE TITLE
Retry logic proposal for the rebuild script

### ISSUE THREAD

**Issue by unbornchikken** [RSATom/WebChimera.js#26]
Hi,

We had a discussion about it there: https://github.com/RSATom/wcjs-ugly-demo/issues/3#issuecomment-119694219

I believe this should work: https://gist.github.com/unbornchikken/a2f1ba9b81ebd707a721

Haven't tried, there maybe mistakes, but the logic is there.

**Comment by RSATom** [comment]
Thank you Gábor! I'll look.

**Comment by unbornchikken** [comment]
I've updated it because I'd missed invocation of the begin method on the end of the script.

**Comment by RSATom** [comment]
Thanks! Anyway didn't look to it yet :)

**Comment by RSATom** [comment]
I had to change your script to get it working: https://gist.github.com/RSATom/3f2aa255fa1e13033fef
Could you please look, if I did something wrong there?

Btw, what is the best way write messages to console?

**Comment by unbornchikken** [comment]
Yeah, you're right, module load error is a synchronous error, so it have to be a regular catch. Printing messages during npm installation is should be done with npmlog module.

**Comment by RSATom** [comment]
Applied, thanks!

**Comment by unbornchikken** [comment]
Had it helped?
________________________________
Feladó: Sergey Radionov<mailto:notifications@github.com>
Feladva: ‎2015.‎07.‎10. 8:34
Címzett: RSATom/WebChimera.js<mailto:WebChimera.js@noreply.github.com>
Másolat: Gábor Mező<mailto:gabor.mezo@outlook.com>
Tárgy: Re: [WebChimera.js] Retry logic proposal for the rebuild script (#26)

Applied, thanks!

---

**Comment by RSATom** [comment]
Yes, but will be 100% sure only after publish to npm (I've tested it with local modified copies of modules)

**Comment by RSATom** [comment]
the interesting thing, on my system it build sucessfull on 3-4 iteration, i.e. only on 3-4 second.

**Comment by unbornchikken** [comment]
But it finally works, right?

**Comment by RSATom** [comment]
yes, it works.

**Comment by unbornchikken** [comment]
I think it's good for q workaround, maybe you could mention in the docs that users could improve install performance by installing cmake-js and WebChimera.js directly in their applications. And when npm 3.0 comes, this issue will gone for sure. I think I've read somewhere that io.js 3.0 will bundle npm 3.0, but not sure about it.

**Comment by RSATom** [comment]
Yea, I think you are right. Don't see any other acceptable solution.
