### ISSUE TITLE
Performance issues with high-quality videos

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#27]
I'm opening the issue so that we address and figure out the performance issues with higher definition videos.

Currently, a common case (@jaruba encountered it, I encountered it too) is a Windows machine (mine was win 8) on which higher definition videos frame heavily in power-save mode. When the machine is plugged in, there's almost no framing, but it's still slightly noticeable. 

Those performance issues are caused mainly by chromium's multi-process architecture, present in both Electron and NW.js, where texImage2D translates into 1 (or maybe 2?) memcpy operations until the texture is in the GPU mem. As opposed to rendering directly to GPU memory like high-performance players can do.

There is one inefficiency currently known in WebChimera.js itself, and it is documented here: https://github.com/RSATom/WebChimera.js/issues/19

The solution is finding a way to render directly to GPU memory, which I'm almost entirely sure cannot be done with current Electron/NW.js.
There is an API in Chromium itself, an internal framework, called GpuMemoryBuffer, which effectively solves the issue, but it's not exposed to the JS side. Maybe we can figure out something with the Electron guys where they integrate an API for the system?

There's a proposed WebGL extension that would solve the issue to - WebGL dynamic texture extension. But it's not going to implemented any time soon, and it's spec is currently rejected.

Some workaround would be nice as a temporary measure. There's some weird factor under power saving mode causing either 1) chromium to screw up texture upload or 2) libvlc to screw up rendering. 1 is much more likely IMO.

Something we can do is give WC.js the temporary ability to create it's own window and draw in it, in the efficient way VLC can. That way we'll officially prove the problem is in Chromium's texture uploads.

Reference links:
https://vec.io/posts/faster-alternatives-to-glreadpixels-and-glteximage2d-in-opengl-es
https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_dynamic_texture/
https://www.khronos.org/registry/gles/extensions/OES/OES_EGL_image.txt
https://groups.google.com/a/chromium.org/forum/m/#!topic/apps-dev/O_k0Tg18668
https://www.chromium.org/developers/design-documents/gpu-command-buffer

https://code.google.com/p/chromium/issues/detail?id=485859 - using GpuMemoryBuffer for rendering video

http://stackoverflow.com/questions/31006399/webgl-asynchronous-teximage2d

Contacts who might help:
http://stackoverflow.com/users/128511/gman

Look into: CHROMIUM_image
##

**Comment by Ivshti** [comment]
Possible bottlenecks in texImage2D in WebGL with Chromium

* "Increasing kMaxTransferBufferSize in src/content/common/gpu/client/webgraphicscontext3d_command_buffer_impl.cc from 16 MB to 128 MB significantly improves performance on this benchmark." - texture buffers > 16 MB would have to be transferred in a few steps
* "The sample above penalizes Chrome's multi-process architecture by performing a glFinish after each texture upload. "
* "The Direct3D 11 back-end uses RGBA formats internally"  - Direct3D 11 vs 9 could be a deciding factor.

References
* https://code.google.com/p/chromium/issues/detail?id=180119
* https://code.google.com/p/angleproject/issues/detail?id=415

**Comment by Ivshti** [comment]
Basically nailed it down to two factors

1) On D3D back-ends (ANGLE) we get our LUMINANCE texture (http://github.com/RSATom/wcjs-renderer) re-packed into an RGBA before it's copied, each channel being copied into four. Which means essentially it's not the penalty of one/two memcpy operations, but instead 4x that. 

2) teximage2D call is blocking the main thread

**Comment by RSATom** [comment]
1) why do you think it's happens on CPU, not inside GPU?

**Comment by Ivshti** [comment]
@RSATom actually I've never thought about this, but the fact is that d3d 11 back-end makes texImage2D a lot slower (maybe 10x)

**Comment by lewmpk** [comment]
I've only just found WebChimera and never used a Raspberry Pi myself, so forgive me if i'm mentioning something already discussed and *please* correct any misunderstandings on my part.

I've been looking into the current situation of this issue for the last few hours and it seems like chromium now supports zero-copy transfers of textures to the GPU process. (If enabled through chrome://flags).

This zero-copy transfer piggybacks off of a feature called 'Native GpuMemoryBuffers' (N-GMB), which your GPU driver has to support. I think I read somewhere that Mesa (Linux GPU driver) doesn't support N-GMB at present (I might of read an old post).

So if a RPI was using a mesa driver with N-GMB support, this should fix the issue. Correct?

Reference:
Notes: https://01.org/blogs/2016/native-one-copy-texture-uploads-for-chrome-OS

**Comment by RSATom** [comment]
@lewmpk, yes, it's possible. But we can't be sure until somebody will try it.

**Comment by lewmpk** [comment]
At least my assumptions were correct. I'll try and confirm. Will update
this issue with my findings

**Comment by jaruba** [comment]
![uu9pmdp](https://cloud.githubusercontent.com/assets/1777923/19644010/1f633ec6-99f6-11e6-9c00-0f81a326cdd1.gif)

**Comment by RSATom** [comment]
It looks like things become worse https://github.com/RSATom/WebChimera.js/issues/110

**Comment by RSATom** [comment]
Closed as too old.
