### ISSUE TITLE
Youtube / Vimeo Links not working

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#31]
I presume it is due to playlist expansion not working on WebChimera.js level.

**Comment by RSATom** [comment]
Thank you, I'm almost forgot about this issue.

**Comment by jaruba** [comment]
Is there no way for this to work with ``Single`` playlist mode?

In ``wcjs-player`` I set ``Single`` when the player is created because I've implemented my own playlist logic.

**Comment by RSATom** [comment]
hm... didn't think about it. I will.
