### ISSUE TITLE
Bug: Library not loaded: @loader_path/lib/libvlc.5.dylib

### ISSUE THREAD

**Issue by nathanredblur** [RSATom/WebChimera.js#33]
Hi.
I'm try to do the most basic example and I have this error in electron or nw. I don't know what else to do.

Code: https://github.com/jaruba/node-vlcPlayer-demo
OS: OSX 10.10.4
Cmake: 3.2.3
Node: 0.12.5
VLC: 2.2.1 (in app folder)

[38175:0802/013606:INFO:CONSOLE(83)] "Uncaught Error: dlopen(/Users/nathanredblur/projects/player/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node, 1): Library not loaded: @loader_path/lib/libvlc.5.dylib
  Referenced from: /Users/nathanredblur/projects/player/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release/WebChimera.js.node
  Reason: image not found", source: /Users/nathanredblur/projects/player/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)
[38175:0802/013612:INFO:CONSOLE(1503)] "Uncaught TypeError: this.find(...).stop is not a function", source: /Users/nathanredblur/projects/player/node_modules/wcjs-player/index.js (1503)

**Comment by RSATom** [comment]
You should extract content of https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip near the `WebChimera.js.node`

**Comment by nathanredblur** [comment]
I don't get it. You mean extract that zip, then that create a folder called ``lib`` then put that folder in /Users/nathanredblur/projects/player/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/

but not work. What is the exactly path in my example?

**Comment by nathanredblur** [comment]
Ok, now I have this error.
[40993:0803/020821:INFO:CONSOLE(83)] "Uncaught Error: Module version mismatch. Expected 44, got 43.", source: /Users/nathanredblur/projects/poly-player/poly-player/node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/bindings/bindings.js (83)
[40993:0803/020827:INFO:CONSOLE(1503)] "Uncaught TypeError: this.find(...).stop is not a function", source: /Users/nathanredblur/projects/poly-player/poly-player/node_modules/wcjs-player/index.js (1503)

what this mean?

**Comment by RSATom** [comment]
this means you have outdated version of `Electron` or `NW.js` (depends what you use)

**Comment by nathanredblur** [comment]
Electron.. 
Thanks I will check that.

**Comment by RSATom** [comment]
you could look used Electron version at https://github.com/RSATom/WebChimera.js/blob/master/build_electron.sh

**Comment by nathanredblur** [comment]
Thanks I go in the right way.

I did this
```
cd node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js
export npm_config_wcjs_runtime="electron"
export npm_config_wcjs_runtime_version="0.30.2"
npm install
```

then again
Download and extract
https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip
into
```
node_modules/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release
```

I can ear the video, but I can't see it. This is the error now.
[00007fb7920c59f8] core vout display error: Failed to change zoom
[00007fb7920c59f8] core vout display error: Failed to set on top
[00007fb7920c59f8] core vout display error: Failed to change source AR

It's because I'm using a new version of Electron?

**Comment by jaruba** [comment]
@nathanredblur I don't think those errors should create any issues, could you try doing ``player.zoom(1)`` when there you don't see any video to see if it solves it?

**Comment by nathanredblur** [comment]
No, I doesn't.
this is what I did
```
<div id="player"></div>
<script>
	var wjs = require("wcjs-player");
	var player = new wjs("#player").addPlayer({ autoplay: true });
	player.zoom(1);
	player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
</script>
```
I will try to upload all the code to github to future reference and code review.

**Comment by RSATom** [comment]
Could you please try this https://github.com/RSATom/wcjs-ugly-demo demo?

**Comment by nathanredblur** [comment]
Sorry, I found the error about why is not showing the video (video element with width and height in 100% BUT inside another div. sorry again.).

but then... what's mean that errors in the console?

**Comment by RSATom** [comment]
it's from libvlc, and it just tell we use output plugin which don't support those features (we use `vmem` plugin)

**Comment by nathanredblur** [comment]
Wonderfull. I think that I can close this. Thank alot for your help and quick response.
