### ISSUE TITLE
onFrameReady triggered when playback is paused

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#35]
``onFrameReady`` still triggers at about 10 FPS of the same frame when playback is paused.

**Comment by RSATom** [comment]
checked, libvlc still render frames even if media is in paused state. Don't sure what I should do with it.

**Comment by jaruba** [comment]
Then maybe this commit in `wcjs-renderer` is the best choice?

https://github.com/RSATom/wcjs-renderer/commit/6f080f90dbc3030421f01bc8a15efa02561e0c23

**Comment by RSATom** [comment]
maybe I can do the same in C++, just don't sure how much overhead I will get if will check state on every play.

**Comment by jaruba** [comment]
It's your choice. :)

It could be simplified in `wcjs-renderer` too, we don't really need to pass the vlc object to the function, we could check if it is playing even before calling the function.

**Comment by RSATom** [comment]
but maybe I can just use `paused` event to raise some flag.

**Comment by jaruba** [comment]
> but maybe I can just use `paused` event to raise some flag.

sounds like the ideal solution

**Comment by RSATom** [comment]
btw, with https://github.com/RSATom/WebChimera.js/commit/576442656dded05cbf7256094bb6592f9367d957 `this === vlcPlayer` inside callbacks (but not with EventEmitter)

**Comment by jaruba** [comment]
Uhm, it's good that you did that, but `wcjs-player` overwrites it by calling `this` as the player api object in cb functions.

**Comment by RSATom** [comment]
but callbacks from renderer still called first?

**Comment by RSATom** [comment]
sorry, closed by mistake

**Comment by RSATom** [comment]
> Uhm, it's good that you did that, but wcjs-player overwrites it by calling this as the player api object in cb functions. :))
Could you please point to code where you do it? It seems I don't fully understand what you do with `this`

**Comment by jaruba** [comment]
https://github.com/jaruba/wcjs-player/blob/master/index.js#L1117-L1121

I save the context in ``saveContext`` then use `.call(saveContext,event)` to overwrite `this` in the cb functions.

**Comment by RSATom** [comment]
as I can see you don't touch `onFrameSetup`, `onFrameReady`, `onFrameCleanup` - so `this` still be equal to `VlcPlayer` instance in `wcjs-renderer`

**Comment by jaruba** [comment]
> but callbacks from renderer still called first?

`wcjs-player` cannot change anything from renderer because it's one level up from it, `this` in cb functions is changed inside `wcjs-player` and all levels down from it.

**Comment by RSATom** [comment]
then we don't need pass `vlcPlayer` to `wcjs-renderer's callbacks with https://github.com/RSATom/WebChimera.js/commit/576442656dded05cbf7256094bb6592f9367d957 anymore. It will simplify renderer a little bit...

**Comment by RSATom** [comment]
but I plan add this changes to `wcjs-renderer` only after new version of `WebChimera.js` will be released.

**Comment by jaruba** [comment]
If frame drawing will be stopped when player is paused from inside `WebChimera.js`, then I don't see any reason for the vlc object to be available in callbacks on the `wcjs-renderer` level, so you can safely remove it.
