### ISSUE TITLE
VlcMedia mrl writable?

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#37]
Would it be possible to have `mrl` from [VlcMedia](https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API#VlcMedia) writable?
##

**Comment by RSATom** [comment]
How do you want use it?

**Comment by jaruba** [comment]
To capture a mrl (that vlc does not support) on opening state, then stopping the player, processing the mrl to convert it to something that vlc can play, replace the mrl (this is where it will be a great improvement to just write to ``mrl`` directly instead of clearing and readding all the items) and playing that item again.

**Comment by RSATom** [comment]
ok, I'll look if it possible.

**Comment by jaruba** [comment]
This would still help me a lot by simplifying a lot of my code. :)

If it could also keep the `.setting` object of the changed playlist items intact, it would be an even bigger code improvement.

**Comment by RSATom** [comment]
Oh... too much work atm... don't sure when could start work on this task :(

**Comment by RSATom** [comment]
Closed as too old.
