### ISSUE TITLE
Error when typing "build_nwjs.cmd" command 

### ISSUE THREAD

**Issue by jounlye** [RSATom/WebChimera.js#39]
Hi guys !

I have a problem with the building of WebChimera.js. 

I'm on Windows 10 and I have installed Git (with Git Bash) and Cmake (added to the Path).
I have an issue when I type this command "build_nwjs.cmd" and I get this error message : 
![image](https://cloud.githubusercontent.com/assets/13719987/9262412/069c3440-4215-11e5-9746-45189e415f93.png)

Please help me !
Thanks, jounlye

**Comment by jaruba** [comment]
Did you manage to build it?

> I have a problem with the building of WebChimera.js.

You also need to install [Visual Studio Community 2013](http://go.microsoft.com/fwlink/?LinkId=517284) in order to build it. :)
