### ISSUE TITLE
YUV instead of RGB

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#4]
Hello,

I implemented I420 in WebChimera
https://github.com/Ivshti/WebChimera.js/tree/yuv

I'm not opening a pull request for now since I want @RSATom to take a look at it. 

Seems to decrease CPU usage 20-30% (e.g from 40% to 29%).
On my system for this HD file, VLC takes 20-30% of one CPU core. WebChimera.js now takes 30-35%, so I think this is an amazing result.

**Comment by RSATom** [comment]
@Ivshti, Wow! It's great! But let me look at it close little bit later. Now I want improve addon api  for frame access. I hope I finish this task this week. After that I will back to I420 issue.

**Comment by RSATom** [comment]
Did you test it with Full HD ?

**Comment by RSATom** [comment]
I've looked your code quickly - and want to say for my opinion you did it right way :) Good job @Ivshti!

**Comment by Ivshti** [comment]
Thanks :) Yes, the figures I'm mentioning are with a full HD video. As I mentioned, 30-35% (of one cpu core) webchimera.js vs 20-30% (one core again) for VLC.

**Comment by RSATom** [comment]
do you have retina display on your mac?

**Comment by Ivshti** [comment]
I have access to a mac with a retina display right now, I'll test it as soon as possible.

**Comment by RSATom** [comment]
could you test some 4k video?

**Comment by Ivshti** [comment]
I don't have a 4k video file right now, I'll download one.
Okay, Macbook Pro with retina, same file: 40-55% WebCbhimera.js, 32-42% VLC. The weird thing is that it shows the Electron process as non-responding. No idea why it does that.

**Comment by Ivshti** [comment]
I tried Big Buck Bunny with 4K resolution, but even VLC can't play it properly on the MBP, so no point of tests for now.

**Comment by RSATom** [comment]
Ok, thanks. Maybe later we will have to try other libraries (gstreamer or libav) to get 4k working well. Good 4k playback should be one of our target.

**Comment by Ivshti** [comment]
What I meant is that the hardware wasn't good enough to play 4K. I also tried quicktime.

But I'm guessing VLC will be just fine with 4K on more capable hardware

**Comment by RSATom** [comment]
I was thought MBP is pretty powerful. What CPU does it have?

**Comment by Ivshti** [comment]
i5 4 cores. The real problem I suspect is the GPU, which really struggles to keep up with the Retina display. In many cases animations are choppy.
There's also an i7 version, also with Nvidia, which I'm guessing would do better.

**Comment by RSATom** [comment]
understand, ok, let's wait better hardware for tests.

**Comment by Ivshti** [comment]
I did something stupid. I guess it happens to everyone. I tested with "Steroscopic 2D" instead of "Standard 2D" which is essentially x2 the resolution.

Downloading Standard 2D, 4K and trying again :)

**Comment by Ivshti** [comment]
Ok. Test results with proper 4K.

WebChimera.js 180 - 270% ; playing smoothly at some points and slightly choppy at others. mostly smoothly
QuickTime - black screen, even though it's supposed to support the codec
Electron - 120-190% -  smooth playback. very slightly choppy, barely noticable
VLC - 130 - 220% - smooth. again, choppy but barely noticable

The overhead in comparison to VLC and especially Electron is pretty noticeable.

**Comment by RSATom** [comment]
So we could declare 4k support already now :)

**Comment by Ivshti** [comment]
I guess. But it definitely needs improvement, since 4K video is a massively resource intensive task, a tiny overhead has a big footprint. 

However, I don't have any specific ideas for improvement. Maybe the webGL context can be somehow optimised? Another idea I have is passing the webgl ctx to the node.js module and doing the re-drawing from there. 

Maybe the garbage collector is doing some damage in collecting old frames?  It doesn't seem like this is possible by reading the source code.

I cannot understand where the overhead comes from :) Seems like WebChimera.js is doing everything right.

**Comment by jaruba** [comment]
> On my system for this HD file: VLC takes 20-30%, WebChimera.js 30-35%

> Test results with proper 4K: VLC - 130-220%, WebChimera.js 180-270%

I may be wrong, but if you do the math between these two tests you've done it looks like WebChimera.js is maintaining the ratio of difference between it and VLC, it's just a really big file so the difference is obviously a lot bigger too, but the ratio does seem to be almost the same in both tests.

**Comment by Ivshti** [comment]
I agree @jaruba. The ratio is more or less the same. That's my point - there isn't much of an overhead, but at 4K the same ratio translates into bigger numbers. Which is starting to be a significant difference.

**Comment by jaruba** [comment]
I don't think that can be optimized in any significant way. With hardware that is meant to play 4K video flawlessly the differences might be a bit smaller, maybe WebChimera.js would be around 180-250% compared to the current results.

You could try using other libraries as @RSATom mentioned but I doubt that the difference will be relevant, it is to be expected that adding another layer to these libraries in order to make them compatible with programs they wore never meant to be used in will create an overhead.. And that the overhead will significantly increase depending on the video resolution.

We must take comfort in the fact that hardware and these libraries continuously evolve, making the CPU usage smaller anyway. This is only the beginning.. and there are not many people that are able to or even desire to play 4K video these days yet. :)

**Comment by jaruba** [comment]
There aren't even that many 4K video sources around the web, so unless NASA is planning to use WebChimera.js for some space project, I think the results are more then OK for the moment. :))

**Comment by RSATom** [comment]
Yes, we don't really need 4K now, but it could be good advertisement if we could mentioned we are capable handle it.

**Comment by Ivshti** [comment]
Moved the code to the master branch
https://github.com/Ivshti/WebChimera.js

**Comment by RSATom** [comment]
Thank you, I'll try finish my current task with events reworking at this weekend.

**Comment by Ivshti** [comment]
Can you share a bit about that? What benefits would it bring?

**Comment by RSATom** [comment]
I just plan move current render callback to property and add `setup`/`cleanup` callbacks same way.

**Comment by RSATom** [comment]
After that I plan start implement same API as http://wiki.webchimera.org/Player_JavaScript_API piece by piece.

**Comment by Ivshti** [comment]
Great :)

I've been thinking, with the V8 API we can have access to the raw OpenGL handles and we can go the next performance level sometimes in the future :) 

I'm looking at QuickTime on OS X and it uses 3-4 % cpu where VLC uses 20-30% and is much more battery efficient. I guess they're doing some directly-to-OpenGL magic. When a suitable library comes along, we could be looking at webchimera.js 2.0 :)

**Comment by RSATom** [comment]
> I've been thinking, with the V8 API we can have access to the raw OpenGL handles and we can go the next performance level sometimes in the future :) 

Unfortunately we don't have access to underling OpenGL context, so we have do all OpenGL calls via JS proxy...

> I'm looking at QuickTime on OS X and it uses 3-4 % cpu where VLC uses 20-30% and is much more battery efficient. 

I think it's just do hardware accelerated decoding, VLC supports it to, but don't know how well and if we could use it too.

**Comment by RSATom** [comment]
@Ivshti, I've wrote you message at https://gitter.im/RSATom/WebChimera

**Comment by RSATom** [comment]
implemented with https://github.com/RSATom/WebChimera.js/commit/0cc96b39a6f47081e4c00b68092d31885783cfcc

**Comment by Ivshti** [comment]
Wait, does that work? How did you do it without a convention shader and 3 textures?

**Comment by RSATom** [comment]
Partially, it shows all black and white :)

**Comment by RSATom** [comment]
I just did't rework demo fully. Your approach with 3 textures is correct and I didn't spend time on it since you already have correct demo.
