### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MikeGCV** [RSATom/WebChimera.js#44]
I'm using wcjs renderer inside an iframe  in electron. Everything is working perfectly, the problem is, every 60 seconds i to have to change the content of the iframe. I destroy it's contents changing the source, before i destroy it i stop the player. I hado to do that because de memory leak was even worse, like 100mb per iteration. Now i have a 10 mb increase per iteration.
Is there a way to completely destroy de player and create a new one?

**Comment by jaruba** [comment]
`WebChimera.js` is never closed in your case, it's just being reinitiated every time you reload the iframe.. All previous module loads are still loaded in the background somewhere.

My suggestion is that you change the logic, you should reuse the same player all the time by stopping it, clearing the playlist and adding the new item, the changes you require from inside the iframe should not reload the page inside the iframe, it should change the data dynamically (ajax, maybe?)

**Comment by jaruba** [comment]
You could try to remove it from the require cache before loading it on the new page though, but I doubt this will fully fix your issue.

Presuming that Electron has the same object reference as NW.js, clearing the cache should be done with something like:

    if (global.require.cache) {
        for (module in global.require.cache) {
            if (global.require.cache.hasOwnProperty(module) && module.indexOf("wcjs-renderer") > -1) delete global.require.cache[module];
        }
    } else if (require.cache) {
        for (module in require.cache) {
            if (require.cache.hasOwnProperty(module) && module.indexOf("wcjs-renderer") > -1) delete require.cache[module];
        }
    }

(this only clears `wcjs-renderer` from the cache, you might also want to clear `webchimera.js` too)

**Comment by MikeGCV** [comment]
@jaruba thank you for your help, still the same, maybe i will have to rethink the app as you suggested in your first sugestion. 
When using a webview, this problem doesn't exist, but i need the content to rotate and then all the rendering inside the webiview goes bananas, except for canvas with wcjs

**Comment by MikeGCV** [comment]
Tweaked around electron's webview and my app. Made it work, Thanks

**Comment by kocokolo** [comment]
load in a seprate proceess  and communite with rpc maybe a choice
