### ISSUE TITLE
EndReached state never happens

### ISSUE THREAD

**Issue by Ivshti** [RSATom/WebChimera.js#45]
The reason is inside jsVlcPlayer.cpp's currentItemEndReached function, which is called when EndReached is received. 

It triggers a .stop(), which stops the player and endreached state can never be received in the client app.

```javascript
    //have to stop to force video_cleanup_cb and as consequence fill frame with black
    player().stop();
```

@jaruba see what hacks lead to  :D

**Comment by jaruba** [comment]
@Ivshti I prefer the black frame over the `EndReached` event,

**Comment by Ivshti** [comment]
@jaruba prefer EndReached or your end will be reached

(*lol, anyone not knowing us would think this is a flame war*)

**Comment by jaruba** [comment]
![3622991-1026104573-azbgk](https://cloud.githubusercontent.com/assets/1777923/9937479/a657ad2e-5d69-11e5-85e4-2b96d0be7d12.gif)

**Comment by Ivshti** [comment]
@RSATom why do we call ``.stop`` to trigger the black frame? Isn't there another way?

**Comment by RSATom** [comment]
without it libvlc doesn't call `video_cleanup_cb` on last playlist item

**Comment by Ivshti** [comment]
Can we just call fill black directly rather than through ``video_cleanup_cb``? Seems like the best solution.

**Comment by RSATom** [comment]
it's not so easy - there are multiple threads there.

**Comment by RSATom** [comment]
@Ivshti, are you sure don't get `EndReached` event. It should be emitted even after stop().

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js/blob/master/src/JsVlcPlayer.cpp#L537
https://github.com/RSATom/WebChimera.js/blob/master/src/JsVlcPlayer.cpp#L586

**Comment by Ivshti** [comment]
@RSATom I am getting it, but state is never set to EndReached

**Comment by RSATom** [comment]
it's just changed to quickly from `EndReached` to `Stopped`, and you have no chance catch it. But I understand you point. Will try to solve it somehow...

**Comment by Ivshti** [comment]
IMO we shouldn't call VLC's stop in an end reached event, since expected libvlc behaviour is to stay forever in EndReached until something is done with it :) 

So in doing that, we're overriding the default behaviour.

As for catching it, I have no debounce, so it should catch it - unless it's lost as early as libuv level, which is probably what happens. Since once you call .stop libvlc will immediately emit stopped.

**Comment by RSATom** [comment]
I should agree, it was bad Idea to use `stop()`....

**Comment by jaruba** [comment]
maybe it's a good idea to remove this implementation from `wcjs` completely and do it manually if needed with `wcjs-renderer` as it can also clear the frame now..

**Comment by Ivshti** [comment]
I agree with @jaruba, wcjs-renderer is a better place for black framing

**Comment by RSATom** [comment]
ok, accepted. Will remove it soon.

**Comment by Ivshti** [comment]
Thanks, awesome
