### ISSUE TITLE
Expose audio stream to js api

### ISSUE THREAD

**Issue by luigiplr** [RSATom/WebChimera.js#47]
Pretty self explanatory :D 
##

**Comment by jaruba** [comment]
+1

**Comment by DevonJames** [comment]
+1

**Comment by RSATom** [comment]
I'll look what I can do. But can't promise could do it soon.

**Comment by jaruba** [comment]
I think only the audio analysis should be exposed, not the stream, as it's best `wcjs` still handles audio playback.

I say this because if the main thread of js gets blocked, it would block the audio too (if played through the audio buffer api in js), while audio still plays in this circumstance when it's done in `wcjs`.

**Comment by smolleyes** [comment]
ola everybody :)

+1 for this (to make something like wavesurfer.js)

ps: how do we access vlcMedia infos ?

**Comment by jaruba** [comment]
@smolleyes hi, it's awesome how you pop up every half a year or so :))

> ps: how do we access vlcMedia infos ?

If your using `WebChimera.js` directly.. then: `player.playlist.items[0]`

if your using `WebChimera.js Player` then: `player.itemDesc(0)` or `player.vlc.playlist.items[0]`

**Comment by Ivshti** [comment]
Let me popup to ruin the party a bit.

Why do I think we need a lower level lib to do this, potentially something on top of libav.

I feel like libvlc is 1) too complicated as a bundle 2) too restricted as an API, even with amem, to do this properly.

What does @RSATom think about this?

**Comment by jaruba** [comment]
@Ivshti 

![funny-creepy-meme-this-tastes-like](https://cloud.githubusercontent.com/assets/1777923/11056836/5b96483c-878e-11e5-99fa-1c17987bf3f8.png)

**Comment by RSATom** [comment]
@Ivshti, I'm already thinking about it... But I think we still could use libvlc, but we will need our own video and audio output plugins. Maybe even based on current vmem/amem plugins.

**Comment by luigiplr** [comment]
this is how i picture @Ivshti 
![](http://maxspliffington.com/wp-content/uploads/2014/09/5ed5c28f9cb04a66c6718ea7efc2afa7e38ac241417978fa6b7d6352f07c4067.jpg)

**Comment by Ivshti** [comment]
Hahaha exactly @luigiplr. Someone has to think of potential issues ;)

**Comment by snify** [comment]
@Ivshti @RSATom 
Isn't it possible to output the audio to localhost as ogg? That would make a nice hack and will work for both electron and nw.js

**Comment by RSATom** [comment]
@snify, don't know, didn't try.

**Comment by RSATom** [comment]
Closed as too old.
