### ISSUE TITLE
Version mismatch in electron 0.33.6 on RPi2

### ISSUE THREAD

**Issue by npenin** [RSATom/WebChimera.js#48]
Hi all,

I have this error when running wcjs-renderer in electron 0.33.6 on a raspberry pi 2.

```
Module version mismatch. Expected 46, got 44.
```

Any clue ?

Thanks.

**Comment by Ivshti** [comment]
You're compiling with the wrong electron version - probably 0.29 - wihle you're trying to run it on 0.33

The solution is either
1) use electron 0.29 
2) re-build with the ./build_electron script, it will set the version to 0.33.x

**Comment by jaruba** [comment]
does electron 0.33.6 support hardware acceleration on the rpi 2?

**Comment by npenin** [comment]
absolutely no idea :p. This what I wanted to try. But now vlc does (since 2.2)

**Comment by RSATom** [comment]
Don't think hardware acceleration could give any benefits in case of `WebChimera.js` since it uses buffer in regular memory to decode video frames. It should use buffer in video memory to get advantage.

**Comment by npenin** [comment]
isn't it possible ? :(

**Comment by jaruba** [comment]
try it :)

**Comment by RSATom** [comment]
@npenin, it still could work, but not as well as on PC

**Comment by npenin** [comment]
i'll try that this evening. I'll let you know.

**Comment by npenin** [comment]
The base issue is fixed, but indeed, no video frame is displayed because of a the raspberry pi speed :(.

**Comment by RSATom** [comment]
Hm... it's strange, you should be able get some video. Maybe with very low fps, but still.

**Comment by RSATom** [comment]
For me, the only way get it working on rpi, is do all based on OpenGL (since x11 doesn't support hardware acceleration atm). One way could be use Qt + QML + Qt WebEngine + QmlVlc

**Comment by npenin** [comment]
I'm basically a .NET Web developper, I absolutely no knowledge at all in Qt. I have downloaded https://github.com/RSATom/QmlVlc. Could you guide me on how to compile/run it ?

**Comment by RSATom** [comment]
tbh, I tried to do it myself some time ago (on first gen rpi), but with no luck, so I recommend you don't waste you time on it.
