### ISSUE TITLE
Audio problems

### ISSUE THREAD

**Issue by alex-rokabilis** [RSATom/WebChimera.js#52]
Hello, first of all this is an excellent work that solves many problems with opensource video playing inside browsers.
I downloaded the wcjs-player demo and i replaced the video url with one of my own http stream server.
Firstly the buffering was slower than html video and vlc. I changed the buffer option in player but it was buffering again and again so 1 second of movie was 5-6 seconds of waiting.(this occures only if you seek inside movie not if you play it from the begging till the end), anyway the real problem was the audio, when i seeked at 50% of movie after buffer completed the audio dissapears, the video is good but no audio at all, you have to seek back,forward,back and if you are lucky the audio starts again. I thought it was a streaming problem so i tryied with a local video file but this happened again.(Video type::mp4)
As i understand vlc is really playing the video and js just showing the frames inside a canvas element, but i can't figure how audio is handled. I tried to see the code but it is in C++ :(
I know only the basics of c++ so i couldn't understand anything.
Please let me know if you have this problem also or at least explain me a bit how audio is handled (just curious).
I am using:: Ubuntu 14.04, nw.js v0.12.3, io.js v1.2.0

**Comment by jaruba** [comment]
I don't have this problem.. are you using the default node.js `http` module to create the streaming server? is the file you are streaming local / remote?

**Comment by RSATom** [comment]
@alex-rokabilis, audio play via libvlc itself, i.e. it's not passed anyhow to browser. Do you use vlc installed from official Ubuntu repo or maybe some PPA?

**Comment by jaruba** [comment]
@alex-rokabilis 

> I changed the buffer option in player but it was buffering again and again so 1 second of movie was 5-6 seconds of waiting.(this occures only if you seek inside movie not if you play it from the begging till the end)

VLC's default `network-cache` is of `600` (= 0.6 sec), I set `wcjs-player`'s default cache to `10000` (10 secs), I did this to eliminate issues such as gray and green frames when getting only partial frames while streaming videos of higher quality (720p, 1080p), so if you set the buffer and want it to be as fast as VLC, you should try values of under `1000`.

Come to think of it, an user did have such a problem and I did manage to reproduce it.. it was with Peerflix links, the issue appeared when skipping forward, then backward through the video, the result was that it would buffer for long times even on parts that wore already downloaded on the server. but that proved to be an issue on the server's side as I could reproduce the exact issue with VLC too.

**Comment by jaruba** [comment]
... or maybe a VLC issue, truth be told, restarting playback would make it work fine again.

**Comment by alex-rokabilis** [comment]
Thank you for your fast answers. I am using the official vlc (revision 2.2.1~trusty1).
As for the http streaming:: In fact i changed a few times the network cache but i couldn't play it as fast and smooth vlc and html does. Also something else happened, when webchimera starts to buffering as mentioned before (1sec movie -- 5sec loading) I let it do that for a minute and ended up restarting(crashing) my nodejs streaming server (this thing never happened before with any other video player) I will post the error logs if that helps.
As for the sound:: If it uses the original vlc audio i cant think why it is stoping.(original vlc never do this) I also used a local file from my disk and the error happened again so it is not a streaming problem. Some vlc errors are appear in terminal when i seek into movie... should i post them??

ps* why my vlc version matters? doesn't this plugin uses the libvlc that already has of its own?

**Comment by jaruba** [comment]
> ps* why my vlc version matters? doesn't this plugin uses the libvlc that already has of its own?

On Linux it actually uses the one that you installed, I didn't have much success in using a custom libvlc on Linux yet..

> Some vlc errors are appear in terminal when i seek into movie... should i post them??

post them..

**Comment by alex-rokabilis** [comment]
when audio dissapears it shows this in terminal::
[000030562fa938b8] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 4077 ms)
[000030562fa938b8] core input error: ES_OUT_RESET_PCR called
Non-reference picture received and no reference available
[h264 @ 0x30562fcd4400] decode_slice_header error
[h264 @ 0x30562fcd4400] mmco: unref short failure
[h264 @ 0x30562fcd4400] mmco: unref short failure
Non-reference picture received and no reference available
[h264 @ 0x30562fcd4400] decode_slice_header error
[h264 @ 0x30562fcd4400] mmco: unref short failure
[h264 @ 0x30562fcd4400] mmco: unref short failure
Non-reference picture received and no reference available
[h264 @ 0x30562fcd4400] decode_slice_header error
Non-reference picture received and no reference available
[h264 @ 0x30562fcd4400] decode_slice_header error
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] reference picture missing during reorder
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] Missing reference picture
[h264 @ 0x30562fcd4400] mmco: unref short failure
[h264 @ 0x30562fcd4400] mmco: unref short failure
[h264 @ 0x30562fcd4400] number of reference frames (0+7) exceeds max (5; probably corrupt input), discarding one


also i see the logs from the nodejs stream server now and when it starts to buffering and loses sound it makes requests for video chunks like crazy...

**Comment by alex-rokabilis** [comment]
@RSATom @jaruba forget everything about the sound, i made several tests with a local file on the original vlc and sometimes the audio is lost. so probably an issue of vlc on linux? or maybe my alsa drivers, not sure but definetely not a webchimera issue. i will try the same on windows.

**Comment by alex-rokabilis** [comment]
audio problem solved with `addPlayer({ vlcArgs: ["--aout=alsa"] })`
forcing alsa audio module instead of pulseaudio which causing me problems.

**Comment by jaruba** [comment]
@alex-rokabilis wow, awesome, i'm glad you found the right vlc argument to fix your issue :)
