### ISSUE TITLE
ASS subtitles support

### ISSUE THREAD

**Issue by sunabozu** [RSATom/WebChimera.js#53]
According to wiki WebChimera.js supports only SUB, SRT and WebVTT. But VLC itself supports pretty much any type of subtitles, including ASS. Is there a particular problem with displaying that format? Do you plan to support it in the future?

**Comment by RSATom** [comment]
The main problem is libvlc doesn't support load subtitles over internet (or at least I didn't find the way to give it right directions to do it), it's only capable load local subtitles. 
So I have two options:
1) download subs inside `WebChimera.js` to some temp folder and feed it to libvlc;
2) allow host application download subs anywhere it likes, and provide some api in `WebChimera.js` to load it;

I don't like 1) since it's not flexible, but I can do 2) without any problem pretty quickly.
The main question is: is 2) will be enough for you?

P.S.: tbh, it's not the only problem with libvlc subs...

**Comment by RSATom** [comment]
> According to wiki WebChimera.js supports only SUB, SRT and WebVTT
Btw, where did you read it? I think it's related to WebChimera/WebChimera.js Player not `WebChimera.js` itself. Player load and show subtitles itself (without using libvlc), that's why it limited.

**Comment by sunabozu** [comment]
I'm currently looking for a way of using it in conjunction with Electron, so I'm not sure which option is suitable for me. I'm kinda confused by variety of APIs.

**Comment by RSATom** [comment]
if you are ready download subs with js and save it somewhere - 2) will fit your needs well

**Comment by jaruba** [comment]
@sunabozu Subtitles are handled by [WebChimera.js Player](https://github.com/jaruba/wcjs-player) in JS:
https://github.com/jaruba/wcjs-player/blob/master/index.js#L1720-L1768

There are many reasons why we're doing this in JS:
- subtitles handled by VLC are under the player's toolbar
- subtitles handled by VLC are usually to big as VLC itself (as an app) understands when it is fullscreen or not and handles sub size differently, but the way we use it, it always thinks it's not fullscreen so when you do go into fullscreen you will see giant subtitles
- subtitles by VLC cannot be styled in CSS or moved in any way
- as @RSATom mentioned, VLC does not support loading subtitles from remote sources

With this said, @vankasteelj shared a function with me at one point of converting `.ass`, `.ssa` and `.txt` subtitles to `.srt` that could be used to extend subtitle support in WebChimera.js Player.

I've posted the function and @vankasteelj gave some details about it on this ticket of a project made with the WebChimera.js Player: https://github.com/oaprograms/lingo-player/issues/1

I've not yet seen any need for this function, nor found the proper files to test it with, if you have access to such files and feel there is a need for such extreme extended subtitle support, you now have all the info required to do it and I would welcome and accept a pull request on [WebChimera.js Player](https://github.com/jaruba/wcjs-player/) if you do manage to do it.

**Comment by sunabozu** [comment]
Ok, so I looked closer at  WebChimera.js and got some clear picture. It appears, what I really need in my project is wcjs-renderer. It works very nice, it renders subtitles internally without JS, and from my perspective it's a good thing, since it natively supports ASS. It also allows to switch subtitle tracks, built in a video file or loaded automatically from a file system by libvlc itself (by a filename - at least that's how I understand it).

So there is only one thing left - loading external subtitles manually. I looked at libvlc sources and found only one function which, apparently, does it. It's called `libvlc_video_set_subtitle_file` and it's located in the [lib/video.c file](https://github.com/videolan/vlc/blob/9053b0919f00d88f16e1ef3e3f79b1cced74f742/lib/video.c#L345). It accepts a path to a file. Looking at WebChimera.js sources I found it inside `libvlc_media_player.h` in libvlc_wrapper. I'm not good at C/C++, especially when such bindings involved, but I tried to add that function to JsVlcVideo.h/cpp and vlc_video.h/cpp files, following existing examples. I managed to compile it, everything works like before, but I can't find that method inside `VlcPlayer` object in JavaScript. Maybe I missed something? Please help me with this.

**Comment by RSATom** [comment]
Please don't lose your time. I'll add it for you tomorow.

**Comment by sunabozu** [comment]
Ok, thank you :)

**Comment by RSATom** [comment]
@sunabozu, function `load` added to `subtitles` by https://github.com/RSATom/WebChimera.js/commit/676c2bb697d827eee63f825bc096c22d7726d3a6

````
var wc = require("webchimera.js");
var vlcPlayer = wc.createPlayer();
vlcPlayer.subtitles.load( path_to_sub );
````

But keep in mind I didn't test it at all. So test it please.

**Comment by sunabozu** [comment]
Wow, that was really fast, thank you again!

It works just as expected, except one thing. I don't know if it's a bug or feature:  when I pass just a wrong path it always returns true. But when I pass a path to a file with a wrong extension (.ass1 for instance) it returns false, doesn't matter if it exists or not. I don't know if's supposed to check a path or it simply checks a file name.

**Comment by RSATom** [comment]
> when I pass just a wrong path it always returns true. But when I pass a path to a file with a wrong extension (.ass1 for instance) it returns false, doesn't matter if it exists or not. I don't know if's supposed to check a path or it simply checks a file name.

It's `libvlc_video_set_subtitle_file` issue, I just forward its return value to JS.

**Comment by RSATom** [comment]
btw, if you will use `WebChimera.js Player` you still could access this API. `WebChimera.js Player` uses `wcjs-renderer` internally.

**Comment by RSATom** [comment]
can we close this issue?

**Comment by sunabozu** [comment]
Yes, problem solved.

**Comment by RSATom** [comment]
thanks
