### ISSUE TITLE
destroy

### ISSUE THREAD

**Issue by xaiki** [RSATom/WebChimera.js#54]
please give us the hability to destroy the wcjs object, or at least unref it so that next init() returns the cached object.
it makes it much easier to have componentized workflow without requiring external (i.e. out of component) state to be kept.

cheers.

**Comment by RSATom** [comment]
Accepted, Thanks!

**Comment by RSATom** [comment]
it seems I've found some time for this issue.
So, could you please elaborate a little bit more, what exactly do you need?

**Comment by xaiki** [comment]
i need to be able to free the VLC object as i may call WCJS from components that are completly destroyed.

**Comment by RSATom** [comment]
so you need something like `player.close()` which will free all libvlc related resources?

**Comment by xaiki** [comment]
exactly, because right now i need to keep external state (in a global variable) to avoid eternal reallocation of vlc contexts.

**Comment by RSATom** [comment]
tbh you don't need keep it. You can create as many players as you like. It will be enough just stop playback, and player instance will be garbage collected some time later (and all allocated resources will be freed).

But anyway, it's not a problem make `close()` public (it's already exists, just don't exported to JS)

**Comment by RSATom** [comment]
`JsPlayer::close()` added: https://github.com/RSATom/WebChimera.js/releases/tag/v0.1.48

check please

**Comment by xaiki** [comment]
cheers !
