### ISSUE TITLE
android version thru jxcore ?

### ISSUE THREAD

**Issue by smolleyes** [RSATom/WebChimera.js#55]
hello :)

do you think a version for android usable thru jxcore (jxcore is very cool thing) is a possibility ? so we can use this with ionicjs / cordova and build awesome mobile audio/video apps

thanks !

**Comment by Ivshti** [comment]
There no way this could possibly happen.

On Android, the rendering systems work totally differently, not to mention android usually runs on ARM which is a completely different thing.

All in all that means we cannot get WebChimera.js with a good performance :(

Plus, jxcore has to be combined with chromium-based runtime to be able to support webchimera.js.

We need a different solution for Android :)

**Comment by luigiplr** [comment]
@Ivshti stahp crushing peoples dreams go.. post some Hitler pics or something :dancer:

**Comment by Ivshti** [comment]
@luigiplr you and I both know that I love pushing technical boundaries. Yet this one is un-pushable, sorry

In all seriousness we do need something like WC.js but for android

Maybe Qt/QML can play a role again. Or the original WebChimera

**Comment by smolleyes** [comment]
np just a question :p thanks for the fast reply anyway !

**Comment by Ivshti** [comment]
and I'm sorry a solution cannot be provided.

We have to maybe update the README to explain this a bit better
