### ISSUE TITLE
core stream error: cannot pre fill buffer

### ISSUE THREAD

**Issue by creativefull** [RSATom/WebChimera.js#63]
hi @RSATom when i play file getting error like this 
```
core stream error: cannot pre fill buffer
```
i'm using Mac

**Comment by RSATom** [comment]
What exactly do you trying to play?

**Comment by creativefull** [comment]
i'm playing video

**Comment by RSATom** [comment]
Does it local file?

**Comment by creativefull** [comment]
yes i'm using local file ,..

**Comment by creativefull** [comment]
when I try to run the application on windows and linux , no problem

**Comment by RSATom** [comment]
Can you play the same file with VLC?

**Comment by creativefull** [comment]
oh yeah u cant play that's file .. :smile: 
file extension is .DAT

**Comment by RSATom** [comment]
Then I'm afraid it's libvlc issue.
