### ISSUE TITLE
libvlc 3.0.0

### ISSUE THREAD

**Issue by dvblogic** [RSATom/WebChimera.js#64]
First of all, thank you very much for your great work!

I am wondering if it would be possible to make webchimera.js to work with libvlc 3.0.0 as opposed to 2.2.1?

We are trying to use the player with transport stream files and proper h265 decoding support is very important for us. libvlc 2.2.1 has very basic support for it. All of the improvements are done in libvlc 3.0.0. Hence the question.

**Comment by RSATom** [comment]
I'll look within couple days. Thanks for report.

**Comment by RSATom** [comment]
@dvblogic, I have some questions:
1. What OS do you use? 
2. Do you use `Electron` or `NW.js`? What version?

I've tried latest nightly VLC ( vlc-3.0.0-git-20151221-0002-win32-debug.7z ) with `Electron` v0.33.9 on Windows - it works for me.

**Comment by dvblogic** [comment]
I am using Electron on Windows and have done essentially the same - substituting vlc dlls from a nightly vlc build. It did not want to start in my case.
I will do a double checking and let you know. Can you please list here the files that you have substituted?
Thanks.

**Comment by RSATom** [comment]
What exactly `Electron` version did you try? Latest `Electron` has compatibility issue libvlc, please read this: https://github.com/RSATom/WebChimera.js/wiki/Electron-v0.36.x-compatibility-issue-on-Windows

**Comment by dvblogic** [comment]
The Electron version that we are using is 0.34.2

**Comment by RSATom** [comment]
ok, I'll try again today with 0.34.2

I've tested it with http://nightlies.videolan.org/build/win32/last/vlc-3.0.0-git-20151221-0002-win32-debug.7z by adding it to the `PATH` environment variable.

I'm on Win10 Pro x64 (but don't think it's matter).

**Comment by RSATom** [comment]
@dvblogic, btw, you could try look libvlc debug messages with https://technet.microsoft.com/en-us/sysinternals/debugview.aspx
Maybe you will see something there.

**Comment by dvblogic** [comment]
Here is an update from our side.
We have made a test application with с vlc-3.0.0-git-20151221-0002-win32 and Electron v0.33.9.

Here are the files that we tried to play:
- http://dveo.com/downloads/TS-sample-files/San_Diego_Clip.ts (transport stream HD mpeg-2 video file)
- http://www.elecard.com/assets/files/other/clips/bbb_360p_c.ts (transport stream SD hevc aka h265 video file)
- http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4 (low resolution mp4 video)

The test application always crashed on the first file on playback start.

On the second file it
- usually crashed
- sometimes started audio-only playback (e.g. without the video)

On the third file it
- sometimes crashed on playback start
- usually started audio-only playback (e.g. without the video)
- sometimes started audio/video playback. This playback was successful until the end if player video is not touched. If window resize was attempted, application crashed.


All in all it looks to me like stability is inverse proportional to video resolution.

All these files play successfully with libvlc 2.2.1 based Electron application.

**Comment by RSATom** [comment]
@dvblogic, thanks! it's very useful info!

**Comment by RSATom** [comment]
Hm... something very strange happening. I've tested all links you provided, and it works for me without any issues.

How I test:
1. `npm install -g electron-prebuilt@0.33.9`
2. download http://nightlies.videolan.org/build/win32/last/vlc-3.0.0-git-20151221-0002-win32-debug.7z , extract, add to `PATH`
3. `git clone https://github.com/RSATom/wcjs-ugly-demo.git`
4. `cd wcjs-ugly-demo`
5. `build_electron.cmd`
6. inside `index.html` replace `player.play("rtmp://video1.earthcam.com:1935/earthcamtv/Stream1");` with `player.play("http://dveo.com/downloads/TS-sample-files/San_Diego_Clip.ts");`
7. `run_electron.cmd`

Could you please do the same?

**Comment by dvblogic** [comment]
Thanks!
We will try and let you know.

**Comment by dvblogic** [comment]
Update from our side.
wcjs-ugly-demo works correctly, indeed. That's good news ;)
The issue happens when wcjs-renderer is used in combination with wcjs-player. Your project uses forked webgl-video-renderer.
Are there any reasons why forked webgl-video-renderer is used in your project? 
Would it be possible/needed to adapt it to use with wcjs-player?

**Comment by RSATom** [comment]
it's really good news.

> Are there any reasons why forked webgl-video-renderer is used in your project? 

just because I want share using it with `WebChimera.js` for GStreamer: https://github.com/RSATom/wcjs-gs

> Would it be possible/needed to adapt it to use with wcjs-player?

no, it should work as-is.

Could you please try https://github.com/jaruba/node-vlcPlayer-demo then? it will be great if it will crash...

**Comment by jaruba** [comment]
> it's really good news.

no it's not.. :))

> it will be great if it will crash...

![jon-snow-sad-gif](https://cloud.githubusercontent.com/assets/1777923/12549551/b4fcee8a-c366-11e5-9e6c-52700a3034de.gif)

**Comment by RSATom** [comment]
@jaruba :)

**Comment by RSATom** [comment]
@dvblogic, I've got the crash. And I think I know the reason. Will try fix it soon.

**Comment by dvblogic** [comment]
Sometimes crash is a good thing ;)

**Comment by RSATom** [comment]
exactly!

**Comment by RSATom** [comment]
I've found the reason of crash and fixed it. But unfortunately there are a bug in libvlc itself which don't allow things work correctly. Will try to do patch for libvlc, but it could take some time...

**Comment by dvblogic** [comment]
Can you, please, share your findings so far?
Thanks.

**Comment by RSATom** [comment]
I use `vmem` libvlc module to decode video frames. It requests memory buffers for video frames. And problem looks like libvlc use wrong buffer to decode specific video frame. I.e. it decode to one buffer, but notify me it used different one.

**Comment by jaruba** [comment]
@RSATom What are our chances of getting a Windows and OSX build of vlc 3.0.0 with vmem and avi stream fix? :))

**Comment by RSATom** [comment]
I think I understand reason of bug with `vmem`, but still working on workaround. Don't sure when it will be available, but I sure it will.

**Comment by RSATom** [comment]
what about avi fix - the only question if I will be able build it for mac, didn't try do it yet.

**Comment by jaruba** [comment]
VLC 3.0.0 apparently fixed my issues.. I'm now interested in switching to it also.. :)

**Comment by RSATom** [comment]
I hope I will have solution within week or two.

**Comment by RSATom** [comment]
https://mailman.videolan.org/pipermail/vlc-devel/2016-January/105832.html

**Comment by dvblogic** [comment]
Cool. Thanks!
I hope it will also fix the issue that we have with wcjs-player crashing on macos when playing ultrahd (hevc video) stream. The symptoms are very close.

**Comment by RSATom** [comment]
@dvblogic, tbh I still don't sure if my patches will be accepted. It's possible I will have to write my own libvlc plugin...

**Comment by RSATom** [comment]
It seems patch will not be accepted. I plan to setup my own build server to not depend from videolan team.

**Comment by dvblogic** [comment]
:( Did they give any reasons why it will not be accepted?..

**Comment by RSATom** [comment]
I think just nobody interested

**Comment by RSATom** [comment]
@dvblogic, could you please test fixed vmem plugin: https://dl.dropboxusercontent.com/u/94817236/libvmem_plugin_v3.0.0a_fixed.zip

**Comment by RSATom** [comment]
I've decided maintain my own copy of `libvlc` `vmem` plugin: https://github.com/RSATom/vmem
downloads: https://github.com/RSATom/vmem/releases (only for Windows and 32 bit atm)

**Comment by dvblogic** [comment]
Does this modification in webchimera.js still requires custom copy of livvlc vmem plugin? Or off-the-shelf libvlc version can be used?

**Comment by RSATom** [comment]
no, it will work with the latest nightly without any changes

**Comment by dvblogic** [comment]
Super. We will check coming week how it works and will let you know. Thanks!
