### ISSUE TITLE
Subtitles are not displayed

### ISSUE THREAD

**Issue by RiderSx** [RSATom/WebChimera.js#65]
They are not displayed when i switching `player.subtitles.track = 1` and if i load external via `player.subtitles.load('C:\\some\\absolute\path\\to\\subs.ass')` i can see that `player.subtitles.count` now `2`, but if i switching don't give much of an effect, `player.subtitles.track` becomes `2` and that's it. But if i open same video and do same (switch to embedded subs, load external and switch to'em) in VLC player it works fine.

Windows 10 64bit
WebChimera.js 0.1.48, 0.2
libvlc 2.2.2 64bit
electron 0.36.5 (with path env variable workaround)

**Comment by RiderSx** [comment]
Log of DebugView on playback start:
![no subs render](https://files.gitter.im/RSATom/WebChimera/XQRj/DebugView-on-__THERS-PC-_local_-2016-02-10-01.39.23.png)

And when subs should be rendered:
![subs render](https://files.gitter.im/RSATom/WebChimera/nPbN/DebugView-on-__THERS-PC-_local_-2016-02-10-01.41.04.png)

**Comment by RSATom** [comment]
try please ia32 version. It's possible it's a bug in libvlc x64

**Comment by RSATom** [comment]
it seems you really should use 32 bit libvlc: https://github.com/Magics-Group/wcjs-renderer/issues/10

**Comment by RiderSx** [comment]
Tried using ia32 version, but got `Uncaught Error: %1 is not a valid Win32 application.
`

**Comment by RiderSx** [comment]
Okay, solved, was using electron x64, with ia32 all good and works.
