### ISSUE TITLE
Snapshot support

### ISSUE THREAD

**Issue by sclem** [RSATom/WebChimera.js#67]
Hi RSATom,

Great work you've done here with WebChimera.js! 

How can I take a snapshot?

I've tried by taking the canvas element and doing `canvas.toDataURL()` but it always returns all black. Is there another way to take a snapshot, perhaps utilizing the videoFrame array?

**Comment by RSATom** [comment]
please read this https://github.com/Magics-Group/wcjs-renderer/pull/7 thread

**Comment by RSATom** [comment]
and some more from gitter.im:
> thereissuchname:
thanks, it worked. But had to torment, just wrapped in a setTimeout(() => { canvas.toDataURL(); ... }, 0) after call onFrameReady

**Comment by RSATom** [comment]
and yes, it's possible use `videoFrame` for this task, it has `I420` pixel format

**Comment by sclem** [comment]
preserveDrawingBuffer worked perfect. Thanks!
