### ISSUE TITLE
Filter documentation --adjust-filter

### ISSUE THREAD

**Issue by sclem** [RSATom/WebChimera.js#68]
RSATom:

the wiki says to use `--adjust-filter=true` when passing vlcArgs, but the correct parameter is `--video-filter=adjust`

**Comment by RSATom** [comment]
It's possible it depends from vlc version. You could edit wiki if you wish, but please try it with vlc 2.2.2 first.

**Comment by sclem** [comment]
I'm using your prebuilt vlc 2.2.2 with nwjs, 64 bit.

**Comment by RSATom** [comment]
maybe it was changed in vlc 2.x, don't sure... then could you please update wiki?

**Comment by sclem** [comment]
Done.

**Comment by RSATom** [comment]
thanks!
