### ISSUE TITLE
Extend JavaScript API

### ISSUE THREAD

**Issue by RSATom** [RSATom/WebChimera.js#7]
Something like this: http://wiki.webchimera.org/Plugin_JavaScript_API

**Comment by Ivshti** [comment]
I guess VLC provides an API to get info about all video / audio / subtitle tracks in the video file? Also, getting the subtitle track with some API?

**Comment by RSATom** [comment]
yes, but better look to `WebChimera` souces: https://github.com/RSATom/WebChimera/blob/master/src/ChimeraAPI.cpp all was already done there.

**Comment by RSATom** [comment]
and it will be better if we will preserve same (as possible) API

**Comment by Ivshti** [comment]
I personally feel a simple .tracks array would be a simpler API :)

**Comment by RSATom** [comment]
how do you plan select some specific track to play?

**Comment by Ivshti** [comment]
Maybe. Now come to think of it, we have to be able to set main video track / audio track (e.g. for dubbed videos).

**Comment by RSATom** [comment]
The one else thing you should think about - most of the tacks properties has meaning only for selected track.

**Comment by Ivshti** [comment]
Okay, maybe this API is out of the question then
But can't VLC read the full info for a track without it being selected?

**Comment by RSATom** [comment]
There not too much info, even for selected tracks :) But tbh, I didn't  investigate this question deeply, so it will be better just look directly to libvlc api: https://github.com/RSATom/libvlc-sdk/tree/master/include/vlc and you could not look to files at ` plugins` folder there - it's api for libvlc plugins only.

**Comment by jaruba** [comment]
In the API Docs there's mention of:

> removeItem(i) -> bool: remove the item from playlist whose identifier is i.

but trying to use it returns:

    Uncaught TypeError: undefined is not a function

**Comment by RSATom** [comment]
@jaruba, I'll check, thanks.

**Comment by RSATom** [comment]
@jaruba, checked with `ugly demo` on linux with `NW.js` by entering `player.playlist.removeItem(10);` to console, and got `false`, i.e. it works as intended. Maybe it's Windows specific issue?

**Comment by jaruba** [comment]
Oh god, I kept trying ``player.removeItem()``, sorry :)

**Comment by RSATom** [comment]
it's good to know it's not one else bug :)

**Comment by RSATom** [comment]
most important APIs implemented (and published to `npm`): `.audio`, `.video`, `.video.deinterlace`, `.subtitles`

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API

**Comment by RSATom** [comment]
if something else required - please notify.

**Comment by Ivshti** [comment]
Seems amazing and pretty complete! 

One thing that I haven't figured about it - can subtitles be read - each individual set of subtitles and then each track within it!

**Comment by jaruba** [comment]
@Ivshti  what do you mean? read the text in the internal subtitle from JS?

**Comment by Ivshti** [comment]
Yes - read the text inside each subtitle track

**Comment by jaruba** [comment]
It would be awesome, but the current api doesn't support that, it just runs the subtitles in VLC's normal mode.

**Comment by RSATom** [comment]
unfortunately there are no way to access subtitle content via libvlc

**Comment by Ivshti** [comment]
Too bad. I was always under the misconception that libvlc is powerful :D

**Comment by RSATom** [comment]
it's powerful, we just don't have access to this power :)

**Comment by RSATom** [comment]
maybe it could be solved via `lua` scripts, don't sure.

**Comment by Ivshti** [comment]
As we discussed multiple times, libvlccore would be nice

**Comment by RSATom** [comment]
Yea, but I still don't know facilities of lua inside vlc, since can't find any docs...

**Comment by Ivshti** [comment]
Is there a way to read video/audio codec?

**Comment by RSATom** [comment]
with libvlc?

**Comment by Ivshti** [comment]
Yes, and with WC.js API

**Comment by RSATom** [comment]
with libvlc - it seems it's possible with libvlc: https://github.com/RSATom/libvlc-sdk/blob/master/include/vlc/libvlc_media.h#L194
but we don't have this in `wcjs`

**Comment by modmanx** [comment]
Great work with this library! I don't want to open new issue - do you maybe have plan to implement "Input object" from http://wiki.webchimera.org/Plugin_JavaScript_API this link? I'm interested on input.rate in specific?

**Comment by jaruba** [comment]
@modmanx
Yes, the ``input`` object will also be added, I already made an issue for it:
https://github.com/RSATom/WebChimera.js/issues/23

**Comment by RSATom** [comment]
@modmanx, yes, `input` object will be implemented on next week

**Comment by RSATom** [comment]
`input` was added. It's already in npm.

**Comment by modmanx** [comment]
@RSATom Amaizing, thank you!

**Comment by RSATom** [comment]
@modmanx, if you will find any issue with it, notify me please.

**Comment by jaruba** [comment]
shouldn't this be closed? doesn't it already have the full api? :)

**Comment by RSATom** [comment]
@jaruba, Don't you need something else?

**Comment by RSATom** [comment]
and btw, we still don't have 
```
.video.contrast
.video.brightness
.video.hue
.video.saturation
.video.gamma
```

**Comment by jaruba** [comment]
> Don't you need something else?

The only difference I can see from the previous player's api compared to ``wcjs-player``'s api atm, is that it's missing ``.onVolume()`` and ``.onMute()``, I already made ``.onState()`` and can also make these 2 missing events too.

But ofc, the full video object would be nice..

**Comment by RSATom** [comment]
onVolumeChanged and onMuteChanged are fake events, same as onStateChanged was.

**Comment by jaruba** [comment]
yes, but they are very helpful, ``.onStateChanged()`` helps with cleaner code, use only one event instead of 10..

``.onVolumeChanged()`` is very helpful in NW.js and Electron, because the volume resets to 100 every time the player is called, and with ``.onVolumeChanged()`` you can save the last volume that was set, and reset it on player initialization to "remember" the volume.

**Comment by RSATom** [comment]
as I mentioned, they are fake events, so you can do them yourself same as I can do it inside .node module.

**Comment by jaruba** [comment]
yeah, their easy to do, already made ``.onState()``

**Comment by RSATom** [comment]
and in such case you will have more control over them...

**Comment by RSATom** [comment]
I just think it will be better implement logic as much as possible with JS, and use C++ only when I have to.

**Comment by jaruba** [comment]
> I just think it will be better implement logic as much as possible with JS, and use C++ only when I have to.

agreed

**Comment by RSATom** [comment]
```
.video.contrast
.video.brightness
.video.hue
.video.saturation
.video.gamma
```
added https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API#VlcVideo
