### ISSUE TITLE
Last version doesn't work on win

### ISSUE THREAD

**Issue by Koncopd** [RSATom/WebChimera.js#70]
Prebuilt WebChimera.js v0.2.1 doesn't work with wcjs-ugly-demo.
System - win 7 x64
Runtime - nwjs-v0.12.3-win-ia32
Lib - WebChimera.js_v0.2.1_nw_v0.12.3_VLC_v2.2.2_ia32_win

After a few seconds nwjs window simply closes.

It worked flawlessly with WebChimera.js_v0.2_nw_v0.12.3_VLC_v2.2.2_ia32_win.

**Comment by RSATom** [comment]
Thank you for report. I'll check it asap.
