### ISSUE TITLE
Travis-CI build for linux is broken

### ISSUE THREAD

**Issue by MikeGCV** [RSATom/WebChimera.js#71]
I see that there is no new builds for electron 0.36+ ,Webchimera doesn't work anymore for this platform?

**Comment by RSATom** [comment]
It works, I just can't get working linux build on Travis-CI. It require some additional work, for which I just don't have time unfortunately.

**Comment by RSATom** [comment]
https://travis-ci.org/RSATom/WebChimera.js/jobs/116663608

**Comment by lyssdod** [comment]
Hi, I've got similar issues with Travis recently. Did you try to build it with newer toolchain, available on trusty (gcc 4.8.4)? You'll need to add this to the top of your `.travis.yml`:

```
dist: trusty
sudo: required
```

**Comment by RSATom** [comment]
@lyssdod, let's try

**Comment by RSATom** [comment]
Looks like [it really works](https://travis-ci.org/RSATom/WebChimera.js/builds/163715782).
Thank you!

**Comment by lyssdod** [comment]
Cool! :)
