### ISSUE TITLE
Crash nw.js with pre built binaries + vlc 0.2.4 on windows

### ISSUE THREAD

**Issue by thereissuchname** [RSATom/WebChimera.js#73]
Crash application after call `require("webchimera.js").createPlayer()`

But if not use vlc libraries in webchimera.js/build/Release (putting VLC in the Path environment variable), it works ok.

Used nw.js 0.14.3 sdk win-x64, latest webchimera prebuilt 0.2.4 with vlc, windows 8.1 x64.
Vlc in the path variable - 2.2.3 x64.

Crashdump:
[http://pastebin.com/NqY3DXkn](http://pastebin.com/NqY3DXkn)

**Comment by RSATom** [comment]
Thanks! I'll check.

**Comment by rayansostenes** [comment]
I'm having the same problem

**Comment by RSATom** [comment]
It's very possible it's the same issue as with latest Electron: https://github.com/RSATom/WebChimera.js/wiki/Electron-v0.36.x-compatibility-issue-on-Windows

**Comment by RSATom** [comment]
Yes, it's the same issue.

To solve it you could use .bat with following content:
```
@echo off

for %%i in ("%~0") do set THIS_BAT_PATH=%%~dpi
set VLC_PLUGIN_PATH=%THIS_BAT_PATH%\node_modules\webchimera.js\build\Release\plugins

nw .
```

**Comment by RSATom** [comment]
Can anybody confirm workaround is working?

**Comment by thereissuchname** [comment]
Sorry, only now could check. Yes, your solution works.

**Comment by RSATom** [comment]
Good. Thanks!
