### ISSUE TITLE
.hasVideo

### ISSUE THREAD

**Issue by jaruba** [RSATom/WebChimera.js#74]
I vaguely remember something like this in the npapi plugin api.

I see a reason for it now, I am currently checking `.fps` but this is unreliable in a lot of situations as there are many online videos that VLC can't get the info for and the fps is set to `0` for these videos too..

**Comment by RSATom** [comment]
[VlcInput::hasVout](https://github.com/RSATom/WebChimera/wiki/QML-API#vlcinput)?

**Comment by jaruba** [comment]
yes, that's the one :))

**Comment by jaruba** [comment]
Is it complicated to do? :(

I would of also tried to see if the renderer is rendering to fix this issue I have with it, but I thought I'd ask first as the renderer is rendering even when paused, so I have a feeling that it might be rendering black frames even if it doesn't have any video output, I haven't checked though, I may be wrong.

**Comment by RSATom** [comment]
No, it's easy. Did you try use it with NPAPI plugin? I just don't sure if it will work.

**Comment by jaruba** [comment]
No, I didn't need it back then, it's the first time I have a use for it.

**Comment by RSATom** [comment]
ok, I'll add it today or tomorrow.

**Comment by RSATom** [comment]
Check please if it works: https://github.com/RSATom/WebChimera.js/commit/6a07963c38fb7f58dfd9e8ddf2ccb3c2fe46734b - I didn't test it.

**Comment by jaruba** [comment]
I can't build it for Electron `v0.37.6` for some reason..

![failed_build](https://cloud.githubusercontent.com/assets/1777923/15137576/6ad736d2-1693-11e6-9850-f74d73233c22.png)

**Comment by RSATom** [comment]
You've forgot init subrepo:
`git submodule update --init --recursive`

**Comment by jaruba** [comment]
That was it. :)

It works beautifully, even when `fps` returns `0`.
![hasvout](https://cloud.githubusercontent.com/assets/1777923/15138225/1759ea1e-1697-11e6-9cab-44b7a81a5076.png)

I also tested it on an audio file and it returns `false`, as it should.

**Comment by RSATom** [comment]
Great! Thanks for testing :)
