### ISSUE TITLE
vlcMedia.duration returns 0 after vlcMedia.parse() but still plays it

### ISSUE THREAD

**Issue by Chayemor** [RSATom/WebChimera.js#75]
I have encountered a problem with ".mpg" videos. Files are parsed and only after `vlcMedia.parsed` is true do I try to access `vlcMedia.duration` It works great with all file formats except ".mpg" (MPEG codec). If I open the video with VLC Player, the duration shows fine, it's when I try to get it through code that it doesn't work. The duration always returns 0 even if I do *setTimeOuts * after parsing. Here is the thing, when played, the duration shows up on the WCJS-PLAYER just fine.

Originally I created this issue in the **wcjs-player** project but redirected it here.

![fbba7a66-15d9-11e6-8d6a-2b198d39c965](https://cloud.githubusercontent.com/assets/3482816/15109487/e6d0a470-15db-11e6-86ac-3066607139eb.png)

**Comment by RSATom** [comment]
What does `.input.length` return while this .mpg is playing?

**Comment by Chayemor** [comment]
What .mpg ?

**Comment by RSATom** [comment]
> I have encountered a problem with ".mpg" videos.

**Comment by RSATom** [comment]
i.e. any with which you've got mentioned above problem.

**Comment by Chayemor** [comment]
hahaha sorry, I completely misundertood it. It returns proper duration: `261920` (ms).

**Comment by RSATom** [comment]
ok, and does `vlcMedia.duration` returns valid duration at the same time?

I think it's just some internal libvlc issue. You could try different VLC version - maybe some of them don't have this issue.

**Comment by Chayemor** [comment]
When video is playing everything seems great. The thing is I have to get duration of a long list of videos at once, I can't be "playing" "stopping" them in order to get their duration. That's why I parse them, then access the metadata. What I don't understand is why `vlcMedia.parsed` is set to **true** but the duration is not accessible until video is played. I am currently using VLC 2.2.1, I'm going to try with 2.2.3.

**Comment by Chayemor** [comment]
No dice, just changed to VLC 2.2.3, **duration **still comes back as** 0** even though **vlcMedia.parsed** states true.

**Comment by RSATom** [comment]
Then it's libvlc bug/issue. I can do nothing with it.

**Comment by jaruba** [comment]
@Chayemor @RSATom it could also be a limitation of VLC's technique of getting the duration on `mpg`  video containers before playback.

@Chayemor Have you tried other `mpg` files in the same circumstance?

**Comment by Chayemor** [comment]
The problem seems to be only with **.mpg** files :( No problem then, I'll come with another way to get the duration. Thanks eitherway!

**Comment by jaruba** [comment]
@Chayemor you can try to see if `ffprobe` gets it correctly

**Comment by Chayemor** [comment]
One of my teammates found something that led to the reason why VLC returns **0**. I don't know if it's in any way possible to fix it via code as I have via de VLC Media Player.

**VLC Media Player**
![6](https://cloud.githubusercontent.com/assets/3482816/15143144/88bca30c-16a8-11e6-9dc6-04bcb89ad6d8.png)

As image shows, VLC is not able to show duration. (To get VLC to look like that just go to **View > Playlist or do Ctrl+L** ) It will after you play the video, but never before.

But if you go to **Tools > Peferences [mark Show settings 'All'] > Demuxers ** change from _Automatic_ to _Avformat demuxer_ , then VLC players is able to show duration previous to playback of video.

![5](https://cloud.githubusercontent.com/assets/3482816/15143255/0fc2a7a2-16a9-11e6-8f5f-3fc96590b307.png)
![2](https://cloud.githubusercontent.com/assets/3482816/15143263/1a24e2c8-16a9-11e6-811e-046d8b1235d8.png)
![3](https://cloud.githubusercontent.com/assets/3482816/15143268/1c24b1c0-16a9-11e6-89b5-763d6df0f53e.png)

Now if you drag the same MPEG file, VLC shows **duration** before playback.

![4](https://cloud.githubusercontent.com/assets/3482816/15143300/3e0d33ac-16a9-11e6-8aef-7fc17e83f256.png)

Now the million dollar question is, is it in any way possible to set the **demuxer** via code?

**Comment by RSATom** [comment]
one way could be remove all other demux plugins, but it will break other formats.

**Comment by RSATom** [comment]
libvlc api just is very limited in many aspects

**Comment by Chayemor** [comment]
Alright, thanks.
