### ISSUE TITLE
VLC prebuilt on OSX has a broken symlink

### ISSUE THREAD

**Issue by guidupuy** [RSATom/WebChimera.js#77]
In `WebChimera.js_v0.2.4_electron_v0.37.8_VLC_v2.2.2_x64_osx.tar.gz` at least (I haven't checked the other releases), the `lib/vlc/lib/liblzma.5.dylib` symlink points to a file that doesn't exist.

While it doesn't cause any problem with the module itself, it does when using webchimera with the `electron-builder` module for packaging...

**Comment by RSATom** [comment]
Thanks! And we should update VLC to v2.2.3...
