### ISSUE TITLE
Is it possible to get the current frame as image?

### ISSUE THREAD

**Issue by snify** [RSATom/WebChimera.js#78]
My idea was to apply CSS animations on the VLC <object>, but it seems it doesn't do anything when I try with Animate.css. Is there a way to get the current frame so I can render it to an element or canvas, so I can animate fully?

**Comment by RSATom** [comment]
Do you need access to single frame or all of them?

**Comment by RSATom** [comment]
If you need single frame, please reed this: https://github.com/Magics-Group/wcjs-renderer/pull/7
If you need all frames, you could work directly with [`WebChimera.js` API](https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API) - it could provide video frames in `I420` or `RV32` (i.e. 32bit RGB) formats.

**Comment by snify** [comment]
I'm a little confused. The example I'm using is creating an application/x-chimera-plugin object and I'm using it directly in nw.js. When I to run the same thing with after "npm install wcjs-renderer" it said: "Uncaught Error: Cannot find module 'wcjs-prebuilt'"
And then I tried to: npm install wcjs-prebuilt and got this error (note that it detects it as electron, but it's nw.js):

> C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master>npm install wcjs-prebuilt
> npm WARN package.json nw-webchimera-demos@ No repository field.
> npm WARN package.json nw-webchimera-demos@ No license field.
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> \
> > wcjs-prebuilt@2.0.8 postinstall C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master\node_modules\wcjs-prebuilt
> > node install.js
> 
> Runtime detected as: electron
> Arch: x64
> Acquiring:  WebChimera.js_electron_0.37.8_x64_win
>   downloading [====================] 100% 0.0s
> Retriving VLC Libs: 2.2 win32
>   downloading [==============------] 71% 4.3sevents.js:85
>       throw er; // Unhandled 'error' event
>             ^
> Error: ENOSPC, write
>     at Error (native)
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "wcjs-prebuilt"
> npm ERR! node v0.12.7
> npm ERR! npm  v2.11.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! wcjs-prebuilt@2.0.8 postinstall: `node install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the wcjs-prebuilt@2.0.8 postinstall script 'node install.js'.
> npm ERR! This is most likely a problem with the wcjs-prebuilt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node install.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls wcjs-prebuilt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master\npm-debug.log
> 
> C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master>

**Comment by snify** [comment]
I'm little confused. I npm installed wcjs-renderer. Then it required wcjd-prebuilt.
I tried to install it with: "set WCJS_PLATFORM=win && set WCJS_ARCH=ia32 && set WCJS_RUNTIME=nw.js && npm install wcjs-prebuilt" but...

> C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master>set WCJS_PLATFORM=win && set WCJS_ARCH=ia32 && set WCJS_RUNTIME=nw.js && npm install wcjs-prebuilt
> npm WARN package.json nw-webchimera-demos@ No repository field.
> npm WARN package.json nw-webchimera-demos@ No license field.
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> \
> > wcjs-prebuilt@2.0.8 postinstall C:\Users\blez\Desktop\nw-webchimera-demos-master\nw-webchimera-demos-master\node_modules\wcjs-prebuilt
> > node install.js
> 
> Runtime detected as: nw.js
> Arch: ia32
> Unsupported runtime/arch/platform
> undefined
> wcjs-prebuilt@2.0.8 node_modules\wcjs-prebuilt
> ├── progress@1.1.8
> ├── find-project-root@1.1.1
> ├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
> ├── mkdirp@0.5.1 (minimist@0.0.8)
> ├── parse-filepath@0.6.3 (map-cache@0.2.2, is-absolute@0.2.5)
> ├── rimraf@2.5.2 (glob@7.0.3)
> ├── bluebird@2.10.2
> ├── unzip@0.1.11 (setimmediate@1.0.4, pullstream@0.4.1, readable-stream@1.0.34, match-stream@0.0.2, fstream@0.1.31, binary@0.3.0)
> ├── decompress-zip@0.2.1 (graceful-fs@4.1.4, mkpath@0.1.0, q@1.4.1, nopt@3.0.6, touch@0.0.3, readable-stream@1.1.14, binary@0.3.0)
> ├── tar-fs@1.12.0 (pump@1.0.1, tar-stream@1.5.2)
> ├── needle@0.10.0 (debug@2.2.0, iconv-lite@0.4.13)
> ├── graceful-ncp@2.0.0 (graceful-fs@3.0.8, ncp@2.0.0, proxyquire@1.7.9)
> ├── request@2.72.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.4.1, node-uuid@1.4.7, combined-stream@1.0.5, qs@6.1.0, tough-cookie@2.2.2, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, http-signature@1.1.1, hawk@3.1.3, har-validator@2.0.6)
> ├── gunzip-maybe@1.3.1 (is-gzip@1.0.0, is-deflate@1.0.0, through2@0.4.2, pumpify@1.3.4, peek-stream@1.1.1, browserify-zlib@0.1.4)
> └── lodash@3.10.1

**Comment by RSATom** [comment]
try `WCJS_RUNTIME=nw`

**Comment by RSATom** [comment]
and it will be better ask wcjs-prebuilt related questions at https://github.com/Ivshti/wcjs-prebuilt

**Comment by RSATom** [comment]
too long time without any activity...
