### ISSUE TITLE
Segmentation fault on OS X (SIGSEGV)

### ISSUE THREAD

**Issue by vsych** [RSATom/WebChimera.js#79]
Hi i'm using webchimera.js in my electron project and sometimes my window becomes white
after investigation i tried webchimera.js in empty node project so here gdb backtrace of segfault. At first i was blaming my hardware but i was able to reproduce on other mac as well.

> Program received signal SIGSEGV, Segmentation fault.
> 0x0000000100916ad0 in uv.async_send ()
> (gdb) backtrace
> #0  0x0000000100916ad0 in uv.async_send ()
> #1  0x0000000100916ac2 in uv_async_send ()
> #2  0x0000000103b130ce in JsVlcPlayer::log_event(int, vlc_log_t const*, char const*, __va_list_tag*) ()
>    from .../node_modules/webchimera.js/build/Release/WebChimera.js.node
> #3  0x0000000103d3d897 in vlc_vaLog ()
>    from .../node_modules/webchimera.js/build/Release/lib/libvlccore.8.dylib
> #4  0x0000000103d3d748 in vlc_Log ()
>    from .../node_modules/webchimera.js/build/Release/lib/libvlccore.8.dylib
> #5  0x0000000103d3d974 in vlc_LogSet ()
>    from .../node_modules/webchimera.js/build/Release/lib/libvlccore.8.dylib
> #6  0x0000000103b1231c in JsVlcPlayer::initLibvlc(v8::Local<v8::Array> const&)
>     ()
>    from .../node_modules/webchimera.js/build/Release/WebChimera.js.node
> #7  0x0000000103b11af2 in JsVlcPlayer::JsVlcPlayer(v8::Local<v8::Object>&, v8::Local<v8::Array> const&) ()
>    from .../node_modules/webchimera.js/build/Release/WebChimera.js.node
> #8  0x0000000103b11541 in JsVlcPlayer::jsCreate(v8::FunctionCallbackInfo<v8::Val---Type <return> to continue, or q <return> to quit---
> ue> const&) ()
>    from .../node_modules/webchimera.js/build/Release/WebChimera.js.node
> #9  0x0000000100186735 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
> #10 0x00000001001dfe9f in v8::internal::Builtin_HandleApiCallConstruct(int, v8::internal::Object**, v8::internal::Isolate*) ()
> #11 0x0000241c6040961b in ?? ()
> #12 0x0000241c60409561 in ?? ()
> #13 0x00007fff5fbff270 in ?? ()
> #14 0x00007fff5fbff2c8 in ?? ()
> #15 0x0000241c60437e86 in ?? ()
> #16 0x00001c0a07b67611 in ?? ()
> #17 0x00002c10cb0b2839 in ?? ()
> #18 0x0000000000000000 in ?? ()

After some code digging i tried commenting out this line 
src/JsVlcPlayer.cpp:367: `libvlc_log_set(_libvlc, JsVlcPlayer::log_event_wrapper, this);`
after compiling everything works fine.

OS X: 10.11.4

JS code: 
  `var wc = require("webchimera.js");`
  `var vlcPlayer = wc.createPlayer();`

**Comment by RSATom** [comment]
Thank you for report! I'll check it asap.

**Comment by RSATom** [comment]
@vsych, what Electron version do you use?

**Comment by RSATom** [comment]
I have one Idea what could be a reason. Is it crash right on startup?

**Comment by jaruba** [comment]
Uhm, I have a crash right on start-up in NW.js 0.12.3 on OSX.. starting the app works 1 out of 3 times.. I always thought it was a NW.js bug though..

**Comment by RSATom** [comment]
@jaruba, good, then it's very possible I know how to fix it.

**Comment by RSATom** [comment]
@vsych, @jaruba, could you please try latest commit from master branch?

**Comment by vsych** [comment]
@RSATom i tried electron@1.1.0, nw.js@0.14.5, node@6.1.0. Also i have stress test starting over and over application and sometimes you can get 10 smooth starts and sometimes 10 crashes in a row.

**Comment by jaruba** [comment]
@vsych yup, that sounds like my bug, it's been seriously annoying my users for the last couple of months..

@RSATom would love to test it, but I don't have OSX :(

**Comment by RSATom** [comment]
@jaruba, unfortunately my Os X installation is broken too, so can't test it myself :( All hopes to @vsych...

**Comment by vsych** [comment]
@RSATom, @jaruba can't reproduce with latest commit  👍

**Comment by jaruba** [comment]
YEY!

![torchlighting](https://cloud.githubusercontent.com/assets/1777923/15453101/7763c3e4-2010-11e6-94b9-9c21f8937ce6.gif)

**Comment by RSATom** [comment]
@vsych, Good news! I'll publish new release couple days later to be sure it's really solved.

**Comment by RSATom** [comment]
published
