### ISSUE TITLE
%1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Zzzen** [RSATom/WebChimera.js#81]
Environment: webchimera-0.2.5-prebuilt, electron-1.2.0-prebuilt, win10 64bit.
Steps to reproduce:
  1. clone https://github.com/jaruba/node-vlcPlayer-demo and run `npm install`.
  2. download WebChimera.js_v0.2.5_electron_v1.2.0_VLC_v2.2.3_x64_win.zip and exact it to the `node_modules` of demo.
  3. rewrite `app.js`
  4. set `"main"` to `"app.js"` in `package.json`
  5. use `node_modules\.bin\electron .` to run the app.

Then a error will be thrown from `node-vlcPlayer-demo\node_modules\bindings\bindings.js:83`

**Comment by jaruba** [comment]
`%1 is not a valid Win32 application` means that your using incorrect architectures.

VLC, WebChimera.js and Electron need to all be the same architecture (`ia32` or `x64`)

I'm not entirely sure if Electron 1.2.0 supports WebChimera.js or not though. But that's what your error means.

**Comment by jaruba** [comment]
btw, the architecture of your windows doesn't matter, only VLC, Webchimera.js and Electron. As you can't use 64bit apps on a 32bit windows, but you can use both 32bit and 64bit apps on a 64bit windows.

**Comment by Zzzen** [comment]
I downloaded WebChimera.js_v0.2.5_electron_v1.2.0_VLC_v2.2.3_x64_win.zip and installed electron-prebuilt_x64.

**Comment by jaruba** [comment]
try it with electron 32bit and webchimera.js + vlc 32bit, maybe the prebuilt was packaged incorrectly..

**Comment by jaruba** [comment]
we recommend using 32bit on windows anyway, 64bit vlc has some bugs that 32bit doesn't..

**Comment by RSATom** [comment]
@Zzzen, did you solve your problem?

**Comment by Zzzen** [comment]
No. After I switched to 32bit, the former error is gone. Now here is some problem with `wjs.addPlayer`:

```
C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\bindings\bindings.js:83 
Uncaught Error: The specified module could not be found. \\?\C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\wcjs-renderer\node_modules\webchimera.js\build\Release\WebChimera.js.node

module.(anonymous function)	@	VM50 ELECTRON_ASAR.js:158
Module._extensions..node	@	VM70 module.js:568
module.(anonymous function)	@	VM50 ELECTRON_ASAR.js:158
Module.load	@	VM70 module.js:456
tryModuleLoad	@	VM70 module.js:415
Module._load	@	VM70 module.js:407
Module.require	@	VM70 module.js:466
require	@	module.js:20
bindings	@	C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\bindings\bindings.js:76
(anonymous function)	@	C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\wcjs-renderer\node_modules\webchime…:1
Module._compile	@	VM70 module.js:541
Module._extensions..js	@	VM70 module.js:550
Module.load	@	VM70 module.js:456
tryModuleLoad	@	VM70 module.js:415
Module._load	@	VM70 module.js:407
Module.require	@	VM70 module.js:466
require	@	module.js:20
init	@	C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\wcjs-renderer\index.js:147
wjs.addPlayer	@	C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\wcjs-player\index.js:447
(anonymous function)	@	index.html:12
```

**Comment by Zzzen** [comment]
I have tried another demo, wcjs-ugly-demo. But I got blank output and zero error message.

**Comment by RSATom** [comment]
@Zzzen, do you use 32bit VLC? Is it in your PATH or near the `WebChimera.js.node`?

**Comment by Zzzen** [comment]
I downloaded this one, `WebChimera.js_v0.2.5_electron_v1.2.0_VLC_v2.2.3_ia32_win.zip`. I saw vlc-dlls inside it. Do I still need to install VLC?

**Comment by RSATom** [comment]
no, you don't. Do you use Electron v1.2.0?

**Comment by RSATom** [comment]
and where exactly do you extract this archive?

**Comment by Zzzen** [comment]
Yes. `npm install --arch=ia32 electron-prebuilt`. And I extracted WebChimera....zip to here, and moved the `webchimera.js` folder to node_modules of demo.

**Comment by RSATom** [comment]
You should've been extract it to `C:\Users\Administrator\Desktop\node-vlcPlayer-demo\node_modules\wcjs-renderer\node_modules\webchimera.js`

**Comment by RSATom** [comment]
i.e. replace this `webchimera.js` folder with new one (or overwrite, it doesn't matter)

**Comment by RSATom** [comment]
another issue you will meet with your `Electron` version is https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

**Comment by Zzzen** [comment]
Great, thank you. it works after I copied that folder. But I have another question, how should specify the path of local video file? `player.addPlaylist("file://E:/4.mp4");` doesn't work, the buffing is always 0%.

**Comment by RSATom** [comment]
`file:///`

**Comment by Zzzen** [comment]
An awesome project!

**Comment by RSATom** [comment]
Thanks. Glad to hear it :)
