### ISSUE TITLE
Are there any efforts to implement PPAPI?

### ISSUE THREAD

**Issue by LukasBombach** [RSATom/WebChimera.js#83]
Hey, are there any efforts to interface WebChimera with Google's Native Client / PPAPI. This would bring native performance to electron / nwjs and allow elements to overlay and interface the video.

**Comment by Ivshti** [comment]
Yes, in theory.

But in practice - it's merely possible.

Please read https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues) first

The same limitations apply to PPAPI, unless they have figured out some magical way to copy/share mem between renderer and gpu processes

**Comment by RSATom** [comment]
@LukasBombach, better ask VLC team about it. I didn't and don't plan work on it.

**Comment by LukasBombach** [comment]
Alright, I get it, thanks guys.
