### ISSUE TITLE
WebChimera not working on Electron (Linux)

### ISSUE THREAD

**Issue by LeoNero** [RSATom/WebChimera.js#85]
Hi. I have the following package.json:
```
{
    "dependencies": {
        "peerflix": "^0.35.1",
        "wcjs-player": "^6.0.0",
        "webchimera.js": "0.2"
 },
  "devDependencies": {
    "electron-prebuilt": "0.36.7"
  }
}

```

and the following index.js:
```
var magnetLink = "magnet link goes here";

var peerflix = require('peerflix');
var wjs = require('wcjs-player');
var player = new wjs("#player").addPlayer({ autoplay: true, wcjs: require('webchimera.js') });
var engine = peerflix(magnetLink);

engine.server.on('listening', function() {
    var myLink = 'http://localhost:' + engine.server.address().port + '/';
    player.addPlaylist(myLink);
});

```

but when I type `./node_modules/.bin/electron .` in the console, no video is playing in my app and the console shows this error message:
`"Uncaught Error: Module version mismatch. Expected 47, got 43.", source: /home/leonardo/test/node_modules/bindings/bindings.js`

What can I do to solve this issue?

**Comment by RSATom** [comment]
@LeoNero you need specify Electron version you want build `WebChimera.js` for.
For example please look: https://github.com/RSATom/WebChimera.js/blob/master/build_electron.sh

**Comment by RSATom** [comment]
> "Uncaught Error: Module version mismatch. Expected 47, got 43."
This error means you try use .node module built for one Electron version with different Electron version

**Comment by LeoNero** [comment]
@RSATom for some reason, webchimera.js version 0.2.5 had been installed.
I changed `"webchimera.js": "0.2"` to `"webchimera.js": "0.2.0"` and now my app works. Thanks!

**Comment by RSATom** [comment]
hm.. Why do you need exactly v0.2.0?

**Comment by LeoNero** [comment]
Because v0.2.0 is the latest version that supports linux, isn't it?

**Comment by RSATom** [comment]
no, latest versions just don't have prebuilt for Linux due to broken travis-ci build script

**Comment by LeoNero** [comment]
Ok! I'll try newer versions later

**Comment by RSATom** [comment]
it looks solved...
