### ISSUE TITLE
Question: Example of using `time` method

### ISSUE THREAD

**Issue by amilajack** [RSATom/WebChimera.js#89]
How can I use the time method to seek a video?

Here's what I essentially have:
```js
const vlc = require('wcjs-prebuilt').createPlayer(); // eslint-disable-line
renderer.bind(element, vlc);
vlc.play(streamingUrl);

vlc.time(30000) // some time in miliseconds
```

**Comment by amilajack** [comment]
Never mind. Found out that mutating vlc.time directly sets the time.

**Comment by RiderSx** [comment]
This is not a method, its a property.

```
vlc.time = 1000; // will seek to 1 second from start
```

**Comment by amilajack** [comment]
Is it possible to change the seek time?

**Comment by RSATom** [comment]
> Is it possible to change the seek time?

Don't understand what you mean.

**Comment by amilajack** [comment]
Is it possible to change the current time of the vlc player?

**Comment by jaruba** [comment]
@amilajack 

```
console.log(vlc.time); // current time of playback in milliseconds
vlc.time = 1000; // set time in milliseconds, current example seeks to 00:01:00

console.log(vlc.position); // current position in playback as float (0.0 to 1.0)
vlc.position = 0.5; // set position as float, current example will seek to 50% of the total duration
```

**Comment by amilajack** [comment]
I am not sure what you mean by 'current position in playback'

**Comment by jaruba** [comment]
video has 03:02:43 length, you watched 01:00:00 of it, then vlc.position will return something like `0.33` (because you watched 33% of the video)

**Comment by amilajack** [comment]
Ohhh got it! Thanks.

**Comment by amilajack** [comment]
Works properly now. Thanks!
