### ISSUE TITLE
Method to kill WebChimera.js

### ISSUE THREAD

**Issue by amilajack** [RSATom/WebChimera.js#90]
Is there a method that can be used to kill vlc and/or WebChimera.js?

**Comment by RiderSx** [comment]
`vlc.close()`?

**Comment by amilajack** [comment]
Does this actually kill the instance tho?

**Comment by RiderSx** [comment]
[I believe it is](https://github.com/RSATom/WebChimera.js/blob/master/src/JsVlcPlayer.cpp#L379-L396)

**Comment by amilajack** [comment]
@RiderSx Thanks!
