### ISSUE TITLE
Video emits audio for a second before being muted

### ISSUE THREAD

**Issue by limoragni** [RSATom/WebChimera.js#94]
I want no audio in my app. I'm using `vlc.audio.mute = true` in order to achieve that. I'm setting that before playing the video. When the video starts it emits audio for a fraction of a second. When I change the video the same happens. Is there a way of mute the video completely?

Thanks!

**Comment by Ivshti** [comment]
I'd guess this is a bug in VLC, since WebChimera.js is merely a wrapper and there's no way that it delays this call 1 second in it's own code. Also, I've encountered it in VLC before.

I'm afraid you'd have to take this up with VLC, or find a workaround - maybe  we should ping @jaruba , the workaround king

did you try setting volume to 0 beforehand?

**Comment by jaruba** [comment]
This is one of those moments where I have to say "you're not gonna like it, though" before I start..

The fact that it happens "on every video" is what makes it strange to me, from my experience `mute` and `volume` are persistent.

So, my question is, are you destroying `WebChimera.js` completely and re-requiring it every time?! If so, don't..

Volume setting limitations are only felt on the very first play after requiring wcjs. There are many such settings that only work after the first ever play. As much as this is a limitation, it can also be easily hacked by playing a short, soundless video on app start (in the background) and setting `mute` or `volume=0`.

A better solution might be experimenting with setting it in the `opening` state, as it's quite possible it will work. If not, try very small timeouts while in the `opening` state. Although the latter of the two feels unreliable as you can't ever be sure of how long the `opening` state will take on different devices.

And just to prove that my creativity can go to absurd lengths if necessary... Check out this crazy thing:
https://github.com/LinusU/node-loudness

**Comment by Ivshti** [comment]
I think it won't go so far, if @limoragni is setting `.audio.mute` then it's normal that this value is video-specific. This bug should go away just by using `.volume` IMO

**Comment by jaruba** [comment]
> This bug should go away just by using .volume IMO

I don't think it would, I'm almost 100% sure that both `mute` and `volume` are persistent.

**Comment by limoragni** [comment]
Thanks for the feedback! 

@jaruba I'm not destroying `WebChimera.js`. 
I hear the sound every time I call `_vlc.play(path)` when I call _`vlc.play()` with no path there's no problem.

I'm setting `mute` and `volume` right after I bind `canvas` and `vlc` to the renderer.

```
  _wcjsRenderer.bind(canvas, _vlc, options);
  _vlc.audio.mute = true;
  _vlc.audio.volume = 0;
```
I will try muting on the opening state. 

And I don't think I could use node-loudness since I want to avoid interrupting the users audio. The scenario is that where they are listening to music while working on the app. So messing with the system wide volume is not an option ;)

**Comment by limoragni** [comment]
I've tried on the `opening` event, with the `setTimeout` and the same happened. The curious thing is that the first play after creating the object is the les lauder and shorter that the ones that come after.

**Comment by RSATom** [comment]
@limoragni, did you try libvlc 3.0?

**Comment by limoragni** [comment]
@RSATom I didn't. I''ve downloaded the last webchimera prebuilt that comes with VLC 2.4.4

Is there a webchimera prebuilt using VLC 3.0 somewhere or I have to download VLC 3 and replace the version I have with that one? Is VLC 3 compatible with webchimera?

**Comment by RSATom** [comment]
You could use WebChimera.js with any libvlc >= 2.1.x (maybe even with 2.0.x - didn't try). Just delete old libvlc files, and place new one.

**Comment by RSATom** [comment]
You could get libvlc 3.0 at http://nightlies.videolan.org/build/win32/

**Comment by limoragni** [comment]
I'm using OSX. Is this the one I have to download? 

http://nightlies.videolan.org/build/macosx-intel/VLCKit-3.0-pre-20160627-0754/

**Comment by RSATom** [comment]
Ah.. Os X... No, you will need extract files from .dmg (like this http://nightlies.videolan.org/build/macosx-intel/vlc-3.0.0-20160718-0341/)

And maybe you will need reorganize files like I do it for prebuilts...

**Comment by RSATom** [comment]
it's libvlc issue
