### ISSUE TITLE
Electron 1.3.0 compatibility (Node.js 6.3.0)

### ISSUE THREAD

**Issue by romaincointepas** [RSATom/WebChimera.js#95]
```
ELECTRON_ASAR.js:158 Uncaught Error: Module version mismatch. Expected 49, got 48.
```

With newly released version of Electron (1.3.0) where Node.js has been updated to 6.3.0.

See https://github.com/electron/electron/releases/tag/v1.3.0

*Note: Webchimera.js was working fine with previous release (1.2.8 using Node.js 6.1.0).*

**Comment by RSATom** [comment]
@romaincointepas, did you build `WebChimera.js` from sources or used prebuillt one?

**Comment by romaincointepas** [comment]
@RSATom Used wcjs-prebuilt.

Also, not sure if that's intended but the macOS build for Electron 1.2.8 `WebChimera.js_v0.2.6_electron_v1.2.8_VLC_v2.2.4_x64_osx.tar.gz` is missing from https://github.com/RSATom/WebChimera.js/releases/tag/v0.2.6. (both `WebChimera.js_v0.2.6_electron_v1.2.8_VLC_v2.2.4_ia32_win.zip` and `WebChimera.js_v0.2.6_electron_v1.2.8_VLC_v2.2.4_x64_win.zip` are there)

**Comment by RSATom** [comment]
`.node` modules are not interchangeable between `Electron`/`NW.js` versions. So you should use `WebChimera.js` built for exactly your engine version.

I've forced rebuild and now it available for `Electron v1.3.0`. Try again please.

**Comment by RSATom** [comment]
> Also, not sure if that's intended but the macOS build for Electron 1.2.8 WebChimera.js_v0.2.6_electron_v1.2.8_VLC_v2.2.4_x64_osx.tar.gz is missing from https://github.com/RSATom/WebChimera.js/releases/tag/v0.2.6.

Yes, some versions could be missing, just because I force rebuild on CI by hand when new version released or somebody request it.

**Comment by romaincointepas** [comment]
`WebChimera.js_v0.2.6_electron_v1.3.0_VLC_v2.2.4_x64_osx.tar.gz` works great for Electron 1.3.0/OSX (will test Windows later), thanks for the build!
