### ISSUE TITLE
Play video backwards

### ISSUE THREAD

**Issue by limoragni** [RSATom/WebChimera.js#96]
Hey! Thanks again for this great library!

I have the need of playing the video backwards as smooth as possible. 

I see there's an `onBackward` event, but I don't see any method that triggers the event. I've tried using the rate with negative numbers, but that's not working.

Is there a way of doing this?

Thanks!

**Comment by RSATom** [comment]
Don't think it supported by libvlc: https://forum.videolan.org/viewtopic.php?t=70191
