### ISSUE TITLE
Compile against electron 1.3.1

### ISSUE THREAD

**Issue by amilajack** [RSATom/WebChimera.js#97]
The latest version of electron that is supported is `1.2.6`. It would be nice if `1.3.x` could be supported as well. I've tested running the version built for electron `1.2.6` against electron `1.3.1` and the audio for mkv files was broken.

**Comment by RSATom** [comment]
rebuild forced on CI...

**Comment by RSATom** [comment]
done

**Comment by amilajack** [comment]
Thanks!
