### ISSUE TITLE
[Rebuild requests]

### ISSUE THREAD

**Issue by RSATom** [RSATom/WebChimera.js#99]
Please add message here if you need `WebChimera.js` for some newer `NW.js` or `Electron`

**Comment by romaincointepas** [comment]
Could you build for the latest Electron (1.4.0 with node 6.5.0) for OS X please? Thanks!

**Comment by RSATom** [comment]
@romaincointepas, build forced.

**Comment by KiresMA** [comment]
Hi,
Could you make builds for the newest NWjs v0.18.1 (Windows ia32 and OSx x64)?
Thanks ahead!

**Comment by RSATom** [comment]
I've published v0.2.7. Builds should be available soon.

**Comment by KiresMA** [comment]
Great, thanks a lot!

**Comment by KiresMA** [comment]
Hello,
Is it possible to publish build for NW v0.18.1 Windows ia32?
We used 18.0 version till now, but there is a problem with renaming nw.exe file.
It was resolved in 18.1, so we have to switch the version of NWjs.

**Comment by RSATom** [comment]
CI can build only for latest NW version (0.18.7 currently) - is it Ok?

**Comment by RSATom** [comment]
Build for windows was forced anyway...

**Comment by KiresMA** [comment]
Hmm.. in NW v0.18.3 Node version was updated to 7.0, so it would be better to stay on 18.1 :)

**Comment by RSATom** [comment]
@KiresMA, then, I'm afraid, it will take some time.

**Comment by KiresMA** [comment]
@RSATom Ok, no problems. Could you tell me how much time it can take?
Is build for Mac 18.7 also time consuming?

**Comment by RSATom** [comment]
Don't know, it depends when I will have some free time.

**Comment by RSATom** [comment]
@KiresMA, btw, why you don't build it yourself?

**Comment by KiresMA** [comment]
I can try to do it, I just don't have Visual Studio and Cmake installed.
I will write you back if I have some problems.

Thanks for your help :)

**Comment by KiresMA** [comment]
Hi!
I made build for NWjs 0.18.1 ia32, works fine for me. If you have time, can I provide you somehow WebChimera.js.node file so you can place it in Releases?

**Comment by RSATom** [comment]
@KiresMA, by security reasons, I place to releases only my own builds, sorry.

**Comment by KiresMA** [comment]
@RSATom I understood you.
In this case, will be waiting for this release when you have free time.

Thank you again

**Comment by romaincointepas** [comment]
@RSATom version 1.5.0 of Electron has been released [(bumping node from 6.5.0 to 7.4.0)](https://github.com/electron/electron/releases/tag/v1.5.0), could you do a new build for mac and windows? Thanks!

**Comment by RSATom** [comment]
Build forced. But keep in mind, I didn't test it with the latest version of Electron. Please notify  me if you will find any issues.

**Comment by romaincointepas** [comment]
@RSATom Sure, I will! Thanks

**Comment by RSATom** [comment]
I don't accept rebuilt requests anymore.
